In [179]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.legend import Legend
import matplotlib.patches as mpatches
import seaborn as sns
#from statsmodels.graphics.mosaicplot import mosaic
import io
import requests

## Lectura de los archivos de test y train

In [180]:
url_test="https://raw.githubusercontent.com/joacols/TP_orga_de_datos/main/Test_TP2_Datos_2020-2C.csv"
s_test=requests.get(url_test).content
df_test=pd.read_csv(io.StringIO(s_test.decode('utf-8')),

#df = pd.read_csv('Entrenamieto_ECI_2020.csv',
dtype={
'ID': np.int64,
'Pricing, Delivery_Terms_Quote_Approval': np.int64,
'Pricing, Delivery_Terms_Approved': np.int64,
'Bureaucratic_Code_0_Approval': np.int64,
'Bureaucratic_Code_0_Approved': np.int64,
'Submitted_for_Approval': np.int64,
'Opportunity_ID': np.int64,
#'Sales_Contract_No': np.int64,
'Delivery_Year': np.int64,
'Total_Power': np.int64,
#'Price':np.float64,
'ASP':np.float64,
'ASP_(converted)':np.float64,
'Total_Amount':np.float64},
parse_dates=[
'Account_Created_Date',
'Planned_Delivery_Start_Date',
'Planned_Delivery_End_Date',
'Opportunity_Created_Date',
'Last_Activity',
'Quote_Expiry_Date',
'Actual_Delivery_Date',
'Last_Modified_Date'
])

df_test.head()

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Month,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Prod_Category_A
0,6140,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 5,Q2,2019,NaT,0,EUR,162240.0,EUR,367419.0,Prod_Category_A_None
1,6146,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 5,Q2,2019,NaT,0,EUR,78624.0,EUR,367419.0,Prod_Category_A_None
2,6151,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 5,Q2,2019,NaT,0,EUR,126555.0,EUR,367419.0,Prod_Category_A_None
3,6118,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 6,Q2,2019,NaT,1,EUR,243360.0,EUR,757783.5,Prod_Category_A_None
4,6124,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 6,Q2,2019,NaT,0,EUR,157248.0,EUR,757783.5,Prod_Category_A_None

In [181]:
url_train="https://raw.githubusercontent.com/joacols/TP_orga_de_datos/main/Train_TP2_Datos_2020-2C.csv"
s_train=requests.get(url_train).content
df_train=pd.read_csv(io.StringIO(s_train.decode('utf-8')),

#df = pd.read_csv('Entrenamieto_ECI_2020.csv',
dtype={
'ID': np.int64,
'Pricing, Delivery_Terms_Quote_Approval': np.int64,
'Pricing, Delivery_Terms_Approved': np.int64,
'Bureaucratic_Code_0_Approval': np.int64,
'Bureaucratic_Code_0_Approved': np.int64,
'Submitted_for_Approval': np.int64,
'Opportunity_ID': np.int64,
#'Sales_Contract_No': np.int64,
'Delivery_Year': np.int64,
'Total_Power': np.int64,
#'Price':np.float64,
'ASP':np.float64,
'ASP_(converted)':np.float64,
'Total_Amount':np.float64},
parse_dates=[
'Account_Created_Date',
'Planned_Delivery_Start_Date',
'Planned_Delivery_End_Date',
'Opportunity_Created_Date',
'Last_Activity',
'Quote_Expiry_Date',
'Actual_Delivery_Date',
'Last_Modified_Date'
])

df_train.head()

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,Q2,2016,NaT,10,EUR,5272800.0,EUR,5272800.0,Closed Lost,Prod_Category_A_None
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,Q1,2016,NaT,0,EUR,48230.0,EUR,48230.0,Closed Won,Prod_Category_A_None
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,Q1,2016,NaT,0,USD,83865.6,USD,83865.6,Closed Won,Prod_Category_A_None
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,14,USD,7421881.5,USD,7421881.5,Closed Lost,Prod_Category_A_None
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,25,USD,13357192.5,USD,13357192.5,Closed Lost,Prod_Category_A_None

## Chequeo de caracteristicas de los set de datos

### Chequeo de dimensiones del set de datos

In [182]:
df_test.shape

(2551, 51)

In [183]:
df_train.shape

(16947, 52)

In [184]:
df_test['Opportunity_ID'].value_counts()

12266    26
10973    24
11089    18
11869    15
11248    11
11827    11
10804    11
11978    10
11280    10
11546    10
12080     9
11236     9
12265     9
12232     9
11830     9
11407     9
12276     9
12117     8
11408     8
10758     8
11870     8
11877     8
11861     8
10914     8
11296     8
11006     8
12286     8
11968     7
10796     7
11609     7
         ..
11402     1
12231     1
12229     1
11764     1
12225     1
11766     1
11768     1
12219     1
12217     1
12215     1
12213     1
11770     1
12209     1
12205     1
12175     1
12203     1
12201     1
12199     1
12197     1
12195     1
11772     1
12191     1
12189     1
11774     1
11776     1
11778     1
12181     1
12179     1
11518     1
11488     1
Name: Opportunity_ID, Length: 1567, dtype: int64

In [185]:
df_train['Opportunity_ID'].value_counts()

12460    36
2008     36
5123     26
6606     26
2911     24
767      18
6654     16
8698     16
6653     16
7568     16
6652     16
4568     16
7565     14
2653     14
6569     14
8293     14
7566     13
5890     13
7859     13
3580     13
1112     12
7604     12
7605     12
6614     12
6804     12
7592     11
6332     11
4288     11
7373     11
192      11
         ..
3416      1
5451      1
3288      1
1241      1
5339      1
3304      1
1257      1
7402      1
5355      1
9453      1
3320      1
1273      1
7418      1
3336      1
1289      1
7434      1
5387      1
9485      1
3352      1
1305      1
3368      1
5419      1
9517      1
3384      1
1337      1
7482      1
5435      1
3400      1
7498      1
0         1
Name: Opportunity_ID, Length: 9841, dtype: int64

In [186]:
#df_test.describe()

## Creacion de nuevas columnas a partir de columnas que contienen fechas

In [187]:
df_train.select_dtypes(include=['datetime']).head()

,Account_Created_Date,Opportunity_Created_Date,Last_Activity,Quote_Expiry_Date,Last_Modified_Date,Planned_Delivery_Start_Date,Planned_Delivery_End_Date,Actual_Delivery_Date
0,2015-06-16,2015-12-07,NaT,2016-01-30,2016-06-13,2016-05-01,2016-06-30,NaT
1,2015-06-16,2015-12-07,NaT,2016-01-20,2016-01-15,2016-01-18,2016-01-20,NaT
2,2015-04-21,2015-12-08,NaT,2016-09-30,2016-09-29,2016-01-25,2016-01-25,NaT
3,2013-07-27,2015-12-08,NaT,NaT,2018-03-27,2018-02-01,2018-03-31,NaT
4,2013-07-27,2015-12-08,NaT,2017-06-02,2018-03-27,2018-02-01,2018-02-28,NaT

In [188]:
df_train['Account_Created_Date_Day'] = df_train['Account_Created_Date'].dt.day
df_train['Account_Created_Date_Month'] = df_train['Account_Created_Date'].dt.month
df_train['Account_Created_Date_Year'] = df_train['Account_Created_Date'].dt.year

df_train['Opportunity_Created_Date_Day'] = df_train['Opportunity_Created_Date'].dt.day
df_train['Opportunity_Created_Date_Month'] = df_train['Opportunity_Created_Date'].dt.month
df_train['Opportunity_Created_Date_Year'] = df_train['Opportunity_Created_Date'].dt.year

df_train['Last_Activity_Day'] = df_train['Last_Activity'].dt.day
df_train['Last_Activity_Month'] = df_train['Last_Activity'].dt.month
df_train['Last_Activity_Year'] = df_train['Last_Activity'].dt.year

df_train['Quote_Expiry_Date_Day'] = df_train['Quote_Expiry_Date'].dt.day
df_train['Quote_Expiry_Date_Month'] = df_train['Quote_Expiry_Date'].dt.month
df_train['Quote_Expiry_Date_Year'] = df_train['Quote_Expiry_Date'].dt.year

df_train['Last_Modified_Date_Day'] = df_train['Last_Modified_Date'].dt.day
df_train['Last_Modified_Date_Month'] = df_train['Last_Modified_Date'].dt.month
df_train['Last_Modified_Date_Year'] = df_train['Last_Modified_Date'].dt.year

df_train['Planned_Delivery_Start_Date_Day'] = df_train['Planned_Delivery_Start_Date'].dt.day
df_train['Planned_Delivery_Start_Date_Month'] = df_train['Planned_Delivery_Start_Date'].dt.month
df_train['Planned_Delivery_Start_Date_Year'] = df_train['Planned_Delivery_Start_Date'].dt.year

df_train['Planned_Delivery_End_Date_Day'] = df_train['Planned_Delivery_End_Date'].dt.day
df_train['Planned_Delivery_End_Date_Month'] = df_train['Planned_Delivery_End_Date'].dt.month
df_train['Planned_Delivery_End_Date_Year'] = df_train['Planned_Delivery_End_Date'].dt.year

df_train['Actual_Delivery_Date_Day'] = df_train['Actual_Delivery_Date'].dt.day
df_train['Actual_Delivery_Date_Month'] = df_train['Actual_Delivery_Date'].dt.month
df_train['Actual_Delivery_Date_Year'] = df_train['Actual_Delivery_Date'].dt.year

###
df_test['Account_Created_Date_Day'] = df_test['Account_Created_Date'].dt.day
df_test['Account_Created_Date_Month'] = df_test['Account_Created_Date'].dt.month
df_test['Account_Created_Date_Year'] = df_test['Account_Created_Date'].dt.year

df_test['Opportunity_Created_Date_Day'] = df_test['Opportunity_Created_Date'].dt.day
df_test['Opportunity_Created_Date_Month'] = df_test['Opportunity_Created_Date'].dt.month
df_test['Opportunity_Created_Date_Year'] = df_test['Opportunity_Created_Date'].dt.year

df_test['Last_Activity_Day'] = df_test['Last_Activity'].dt.day
df_test['Last_Activity_Month'] = df_test['Last_Activity'].dt.month
df_test['Last_Activity_Year'] = df_test['Last_Activity'].dt.year

df_test['Quote_Expiry_Date_Day'] = df_test['Quote_Expiry_Date'].dt.day
df_test['Quote_Expiry_Date_Month'] = df_test['Quote_Expiry_Date'].dt.month
df_test['Quote_Expiry_Date_Year'] = df_test['Quote_Expiry_Date'].dt.year

df_test['Last_Modified_Date_Day'] = df_test['Last_Modified_Date'].dt.day
df_test['Last_Modified_Date_Month'] = df_test['Last_Modified_Date'].dt.month
df_test['Last_Modified_Date_Year'] = df_test['Last_Modified_Date'].dt.year

df_test['Planned_Delivery_Start_Date_Day'] = df_test['Planned_Delivery_Start_Date'].dt.day
df_test['Planned_Delivery_Start_Date_Month'] = df_test['Planned_Delivery_Start_Date'].dt.month
df_test['Planned_Delivery_Start_Date_Year'] = df_test['Planned_Delivery_Start_Date'].dt.year

df_test['Planned_Delivery_End_Date_Day'] = df_test['Planned_Delivery_End_Date'].dt.day
df_test['Planned_Delivery_End_Date_Month'] = df_test['Planned_Delivery_End_Date'].dt.month
df_test['Planned_Delivery_End_Date_Year'] = df_test['Planned_Delivery_End_Date'].dt.year

df_test['Actual_Delivery_Date_Day'] = df_test['Actual_Delivery_Date'].dt.day
df_test['Actual_Delivery_Date_Month'] = df_test['Actual_Delivery_Date'].dt.month
df_test['Actual_Delivery_Date_Year'] = df_test['Actual_Delivery_Date'].dt.year

In [189]:
df_train[['Month','Delivery_Year']].head()

      Month  Delivery_Year
0  2016 - 5           2016
1  2016 - 1           2016
2  2016 - 1           2016
3  2018 - 2           2018
4  2018 - 2           2018

In [190]:
df_train["Delivery_Month"] = df_train['Month'].map(lambda x: x.split('-')[1])
df_train = df_train.astype({"Delivery_Month": np.int8})

df_train["Delivery_Month"].head()

0    5
1    1
2    1
3    2
4    2
Name: Delivery_Month, dtype: int8

In [191]:
df_test["Delivery_Month"] = df_test['Month'].map(lambda x: x.split('-')[1])
df_test = df_test.astype({"Delivery_Month": np.int8})

df_test["Delivery_Month"].head()

0    5
1    5
2    5
3    6
4    6
Name: Delivery_Month, dtype: int8

Delivery_Quarter es la columna que describe el cuatrimestre de entrega. En lugar de que sea texto solo dejarÃ© el numero de cuatrimestre( esto resultarÃ¡ Ãºtil para los modelos que solo trabajen con datos numÃ©ricos)

In [192]:
df_train['Delivery_Quarter'].value_counts()

Q2    4443
Q1    4317
Q4    4144
Q3    4043
Name: Delivery_Quarter, dtype: int64

In [193]:
df_train['Delivery_Quarter']=df_train['Delivery_Quarter'].str.slice(start=-1).astype(float)
df_train['Delivery_Quarter'].value_counts()

2.0    4443
1.0    4317
4.0    4144
3.0    4043
Name: Delivery_Quarter, dtype: int64

In [194]:
df_test['Delivery_Quarter']=df_test['Delivery_Quarter'].str.slice(start=-1).astype(float)

## CodificaciÃ³n de algunas variables categoricas

Cada oportunidad puede tener mÃ¡s de un item 
y en particular los items tienen dos variables categoricas que son el nombre y la familia.
Cuando agrupemos por oportunidad buscaremos valores representativos de todos los items asociados a esa oportunidad.
Generalmente aplicamos funciones numericas, motivo por el cual necesitaremos codificar estas dos variables categÃ³ricas como nÃºmeros.

In [195]:
import category_encoders as ce
encoder_family=ce.BinaryEncoder(cols=['Product_Family'])
df_train_bin1=encoder_family.fit_transform(df_train['Product_Family'])
df_train_bin1=df_train_bin1.add_prefix('Bit_')

encoder_name=ce.BinaryEncoder(cols=['Product_Name'])
df_train_bin2=encoder_name.fit_transform(df_train['Product_Name'])
df_train_bin2=df_train_bin2.add_prefix('Bit_')

df_train_encodeado=pd.concat([df_train,df_train_bin1,df_train_bin2],axis=1)
df_train_encodeado.head()

#from sklearn.preprocessing import LabelBinarizer
#lb = LabelBinarizer()
#df_train_bin=lb.fit_transform(df_train['Product_Family'])
#pd.concat([df_train,pd.DataFrame(df_train_bin)],axis=1)

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Bit_Product_Name_0,Bit_Product_Name_1,Bit_Product_Name_2,Bit_Product_Name_3,Bit_Product_Name_4,Bit_Product_Name_5,Bit_Product_Name_6,Bit_Product_Name_7,Bit_Product_Name_8,Bit_Product_Name_9
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,0,0,0,0,0,0,0,0,0,1
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,0,0,0,0,0,0,0,0,1,0
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,0,0,0,0,0,0,0,0,1,1
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,0,0,0,0,0,0,0,1,0,0
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,0,0,0,0,0,0,0,1,0,0

In [196]:
df_test_bin1=encoder_family.fit_transform(df_test['Product_Family'])
df_test_bin1=df_test_bin1.add_prefix('Bit_')

df_test_bin2=encoder_name.fit_transform(df_test['Product_Name'])
df_test_bin2=df_test_bin2.add_prefix('Bit_')

df_test_encodeado=pd.concat([df_test,df_test_bin1,df_test_bin2],axis=1)
df_test_encodeado.head()

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Bit_Product_Family_7,Bit_Product_Name_0,Bit_Product_Name_1,Bit_Product_Name_2,Bit_Product_Name_3,Bit_Product_Name_4,Bit_Product_Name_5,Bit_Product_Name_6,Bit_Product_Name_7,Bit_Product_Name_8
0,6140,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,0,0,0,0,0,0,0,0,1
1,6146,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,0,0,0,0,0,0,0,0,1,0
2,6151,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,0,0,0,0,0,0,0,1,1
3,6118,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,0,0,0,0,0,0,1,0,0
4,6124,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,0,0,0,0,0,0,0,0,1,0

### Chequeo de nombres de columnas

In [197]:
df_test_encodeado.columns

Index(['ID', 'Region', 'Territory', 'Pricing, Delivery_Terms_Quote_Appr',
       'Pricing, Delivery_Terms_Approved', 'Bureaucratic_Code_0_Approval',
       'Bureaucratic_Code_0_Approved', 'Submitted_for_Approval',
       'Bureaucratic_Code', 'Account_Created_Date', 'Source ',
       'Billing_Country', 'Account_Name', 'Opportunity_Name', 'Opportunity_ID',
       'Sales_Contract_No', 'Account_Owner', 'Opportunity_Owner',
       'Account_Type', 'Opportunity_Type', 'Quote_Type', 'Delivery_Terms',
       'Opportunity_Created_Date', 'Brand', 'Product_Type', 'Size',
       'Product_Category_B', 'Price', 'Currency', 'Last_Activity',
       'Quote_Expiry_Date', 'Last_Modified_Date', 'Last_Modified_By',
       'Product_Family', 'Product_Name', 'ASP_Currency', 'ASP',
       'ASP_(converted)_Currency', 'ASP_(converted)',
       'Planned_Delivery_Start_Date', 'Planned_Delivery_End_Date', 'Month',
       'Delivery_Quarter', 'Delivery_Year', 'Actual_Delivery_Date', 'TRF',
       'Total_Amount_Currency', 'Total_Amount',
       'Total_Taxable_Amount_Currency', 'Total_Taxable_Amount',
       'Prod_Category_A', 'Account_Created_Date_Day',
       'Account_Created_Date_Month', 'Account_Created_Date_Year',
       'Opportunity_Created_Date_Day', 'Opportunity_Created_Date_Month',
       'Opportunity_Created_Date_Year', 'Last_Activity_Day',
       'Last_Activity_Month', 'Last_Activity_Year', 'Quote_Expiry_Date_Day',
       'Quote_Expiry_Date_Month', 'Quote_Expiry_Date_Year',
       'Last_Modified_Date_Day', 'Last_Modified_Date_Month',
       'Last_Modified_Date_Year', 'Planned_Delivery_Start_Date_Day',
       'Planned_Delivery_Start_Date_Month', 'Planned_Delivery_Start_Date_Year',
       'Planned_Delivery_End_Date_Day', 'Planned_Delivery_End_Date_Month',
       'Planned_Delivery_End_Date_Year', 'Actual_Delivery_Date_Day',
       'Actual_Delivery_Date_Month', 'Actual_Delivery_Date_Year',
       'Delivery_Month', 'Bit_Product_Family_0', 'Bit_Product_Family_1',
       'Bit_Product_Family_2', 'Bit_Product_Family_3', 'Bit_Product_Family_4',
       'Bit_Product_Family_5', 'Bit_Product_Family_6', 'Bit_Product_Family_7',
       'Bit_Product_Name_0', 'Bit_Product_Name_1', 'Bit_Product_Name_2',
       'Bit_Product_Name_3', 'Bit_Product_Name_4', 'Bit_Product_Name_5',
       'Bit_Product_Name_6', 'Bit_Product_Name_7', 'Bit_Product_Name_8'],
      dtype='object')

In [198]:
df_train_encodeado.columns

Index(['ID', 'Region', 'Territory', 'Pricing, Delivery_Terms_Quote_Appr',
       'Pricing, Delivery_Terms_Approved', 'Bureaucratic_Code_0_Approval',
       'Bureaucratic_Code_0_Approved', 'Submitted_for_Approval',
       'Bureaucratic_Code', 'Account_Created_Date', 'Source ',
       'Billing_Country', 'Account_Name', 'Opportunity_Name', 'Opportunity_ID',
       'Sales_Contract_No', 'Account_Owner', 'Opportunity_Owner',
       'Account_Type', 'Opportunity_Type', 'Quote_Type', 'Delivery_Terms',
       'Opportunity_Created_Date', 'Brand', 'Product_Type', 'Size',
       'Product_Category_B', 'Price', 'Currency', 'Last_Activity',
       'Quote_Expiry_Date', 'Last_Modified_Date', 'Last_Modified_By',
       'Product_Family', 'Product_Name', 'ASP_Currency', 'ASP',
       'ASP_(converted)_Currency', 'ASP_(converted)',
       'Planned_Delivery_Start_Date', 'Planned_Delivery_End_Date', 'Month',
       'Delivery_Quarter', 'Delivery_Year', 'Actual_Delivery_Date', 'TRF',
       'Total_Amount_Currency', 'Total_Amount',
       'Total_Taxable_Amount_Currency', 'Total_Taxable_Amount', 'Stage',
       'Prod_Category_A', 'Account_Created_Date_Day',
       'Account_Created_Date_Month', 'Account_Created_Date_Year',
       'Opportunity_Created_Date_Day', 'Opportunity_Created_Date_Month',
       'Opportunity_Created_Date_Year', 'Last_Activity_Day',
       'Last_Activity_Month', 'Last_Activity_Year', 'Quote_Expiry_Date_Day',
       'Quote_Expiry_Date_Month', 'Quote_Expiry_Date_Year',
       'Last_Modified_Date_Day', 'Last_Modified_Date_Month',
       'Last_Modified_Date_Year', 'Planned_Delivery_Start_Date_Day',
       'Planned_Delivery_Start_Date_Month', 'Planned_Delivery_Start_Date_Year',
       'Planned_Delivery_End_Date_Day', 'Planned_Delivery_End_Date_Month',
       'Planned_Delivery_End_Date_Year', 'Actual_Delivery_Date_Day',
       'Actual_Delivery_Date_Month', 'Actual_Delivery_Date_Year',
       'Delivery_Month', 'Bit_Product_Family_0', 'Bit_Product_Family_1',
       'Bit_Product_Family_2', 'Bit_Product_Family_3', 'Bit_Product_Family_4',
       'Bit_Product_Family_5', 'Bit_Product_Family_6', 'Bit_Product_Family_7',
       'Bit_Product_Family_8', 'Bit_Product_Name_0', 'Bit_Product_Name_1',
       'Bit_Product_Name_2', 'Bit_Product_Name_3', 'Bit_Product_Name_4',
       'Bit_Product_Name_5', 'Bit_Product_Name_6', 'Bit_Product_Name_7',
       'Bit_Product_Name_8', 'Bit_Product_Name_9'],
      dtype='object')

In [199]:
#df_train_encodeado.info()

In [200]:
#df_test_encodeado.info()

## Agrupamiento de los datos por Opportunity_ID

In [201]:
test_agrupado = df_test_encodeado.groupby([
'Region',
'Territory',
'Pricing, Delivery_Terms_Quote_Appr',
'Pricing, Delivery_Terms_Approved',
'Bureaucratic_Code_0_Approval',
'Bureaucratic_Code_0_Approved',
'Submitted_for_Approval',
'Bureaucratic_Code',
#'Account_Created_Date',
'Account_Created_Date_Day',
'Account_Created_Date_Month',
'Account_Created_Date_Year',
'Source ',
'Billing_Country',
'Account_Name',
'Opportunity_Name',
'Opportunity_ID',
'Sales_Contract_No',
'Account_Owner',
'Opportunity_Owner',
'Account_Type',
'Opportunity_Type',
'Quote_Type',
'Delivery_Terms',
#'Opportunity_Created_Date',
'Opportunity_Created_Date_Day', 
'Opportunity_Created_Date_Month',
'Opportunity_Created_Date_Year', 
'Brand',
'Product_Type',
'Size',
'Product_Category_B',
'Price',
'Currency',
#'Last_Modified_Date',
'Last_Modified_Date_Day', 
'Last_Modified_Date_Month',
'Last_Modified_Date_Year', 
'Last_Modified_By',    
'Total_Amount_Currency',
'Total_Taxable_Amount_Currency',
'Total_Taxable_Amount',
#'Stage',  #test no tiene stage (que es la columna a predecir)
'Prod_Category_A'
    
]).agg(
                                  {'TRF': ['mean','std','min','max'], 
                                   'Total_Amount': ['mean','std','min','max'],
                                   
                                   #'Last_Activity':['min','max'],#esta columna tiene todos valores null 
                                                                 #ver si conviene sacarla        

                                   'Last_Activity_Day': ['mean','std','min','max'],
                                   'Last_Activity_Month': ['mean','std','min','max'], 
                                   'Last_Activity_Year': ['mean','std','min','max'], 
                                   
                                   #'Quote_Expiry_Date':['min','max'],
                                   'Quote_Expiry_Date_Day': ['mean','std','min','max'],
                                   'Quote_Expiry_Date_Month': ['mean','std','min','max'], 
                                   'Quote_Expiry_Date_Year': ['mean','std','min','max'],
                                   
                                   #'Product_Family':?,
                                   #'Product_Name':?,
                                   'Bit_Product_Family_0': ['mean','std','min','max'], 
                                   'Bit_Product_Family_1': ['mean','std','min','max'],
                                   'Bit_Product_Family_2': ['mean','std','min','max'], 
                                   'Bit_Product_Family_3': ['mean','std','min','max'], 
                                   'Bit_Product_Family_4': ['mean','std','min','max'],
                                   'Bit_Product_Family_5': ['mean','std','min','max'], 
                                   'Bit_Product_Family_6': ['mean','std','min','max'], 
                                   'Bit_Product_Family_7': ['mean','std','min','max'],
                                   
                                   'Bit_Product_Name_0': ['mean','std','min','max'], 
                                   'Bit_Product_Name_1': ['mean','std','min','max'], 
                                   'Bit_Product_Name_2': ['mean','std','min','max'],
                                   'Bit_Product_Name_3': ['mean','std','min','max'], 
                                   'Bit_Product_Name_4': ['mean','std','min','max'], 
                                   'Bit_Product_Name_5': ['mean','std','min','max'],
                                   'Bit_Product_Name_6': ['mean','std','min','max'], 
                                   'Bit_Product_Name_7': ['mean','std','min','max'], 
                                   'Bit_Product_Name_8': ['mean','std','min','max'],
                                   
                                   'ASP':['mean','std','min','max'],
                                   'ASP_Currency':'max',
                                   'ASP_(converted)': ['mean','std','min','max'],
                                   'ASP_(converted)_Currency':'max',
                                   
                                   'Delivery_Quarter':['mean','std','min','max'],
                                   'Delivery_Year':['mean','std','min','max'],
                                   'Delivery_Month':['mean','std','min','max'],
                                   #'Actual_Delivery_Date':['min','max'],#esta columna tienen todos valores null 
                                                                         #ver si conviene sacarla
                                   'Actual_Delivery_Date_Day':['mean','std','min','max'],
                                   'Actual_Delivery_Date_Month': ['mean','std','min','max'],
                                   'Actual_Delivery_Date_Year':['mean','std','min','max'],
                                   
                                   #'Planned_Delivery_Start_Date':['min','max'],
                                   'Planned_Delivery_Start_Date_Day':['mean','std','min','max'],
                                   'Planned_Delivery_Start_Date_Month':['mean','std','min','max'], 
                                   'Planned_Delivery_Start_Date_Year':['mean','std','min','max'],
                                   #'Planned_Delivery_End_Date':['min','max'],
                                   'Planned_Delivery_End_Date_Day':['mean','std','min','max'], 
                                   'Planned_Delivery_End_Date_Month':['mean','std','min','max'],
                                   'Planned_Delivery_End_Date_Year':['mean','std','min','max'],                                    
                                   
                                   'Opportunity_ID':'count' #cantidad de items por oportunidad
                                  })#.reset_index()

#lo que quiero es agrupar por opportunity_ID y categoricos iguales y promediar los numericos

#df_train.dtypes
#transformo los multiindices en un indice de un solo nivel
test_level0=test_agrupado.columns.get_level_values(0)
test_level1=test_agrupado.columns.get_level_values(1)
test_agrupado.columns=test_level0+'_'+test_level1
test_agrupado.reset_index(inplace=True)
test_agrupado.rename(columns={'Opportunity_ID_count':'Items_by_opportunity'},inplace=True)
test_agrupado.rename(columns={'ASP_Currency_max':'ASP_Currency'},inplace=True)
test_agrupado.rename(columns={'ASP_(converted)_Currency_max':'ASP_(converted)_Currency'},inplace=True)
test_agrupado

,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date_Day,Account_Created_Date_Month,...,Planned_Delivery_End_Date_Day_max,Planned_Delivery_End_Date_Month_mean,Planned_Delivery_End_Date_Month_std,Planned_Delivery_End_Date_Month_min,Planned_Delivery_End_Date_Month_max,Planned_Delivery_End_Date_Year_mean,Planned_Delivery_End_Date_Year_std,Planned_Delivery_End_Date_Year_min,Planned_Delivery_End_Date_Year_max,Items_by_opportunity
0,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,20,2,...,31.0,12.0,0.0,12.0,12.0,2019.0,0.0,2019.0,2019.0,2
1,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,22,8,...,31.0,12.0,NaN,12.0,12.0,2019.0,NaN,2019.0,2019.0,1
2,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,22,8,...,31.0,3.0,0.0,3.0,3.0,2019.0,0.0,2019.0,2019.0,8
3,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,4,4,...,28.0,6.0,0.0,6.0,6.0,2019.0,0.0,2019.0,2019.0,9
4,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,4,4,...,28.0,6.0,0.0,6.0,6.0,2019.0,0.0,2019.0,2019.0,6
5,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,20,2,...,30.0,6.0,0.0,6.0,6.0,2019.0,0.0,2019.0,2019.0,2
6,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,20,2,...,30.0,6.0,0.0,6.0,6.0,2019.0,0.0,2019.0,2019.0,7
7,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,20,2,...,30.0,6.0,0.0,6.0,6.0,2019.0,0.0,2019.0,2019.0,4
8,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,20,2,...,31.0,3.0,0.0,3.0,3.0,2019.0,0.0,2019.0,2019.0,2
9,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,20,2,...,31.0,3.0,0.0,3.0,3.0,2019.0,0.0,2019.0,2019.0,2
10,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,20,2,...,31.0,3.0,NaN,3.0,3.0,2019.0,NaN,2019.0,2019.0,1
11,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,22,3,...,30.0,9.0,0.0,9.0,9.0,2019.0,0.0,2019.0,2019.0,2
12,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,22,8,...,31.0,12.0,0.0,12.0,12.0,2019.0,0.0,2019.0,2019.0,4
13,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,22,8,...,30.0,6.0,0.0,6.0,6.0,2019.0,0.0,2019.0,2019.0,4
14,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,22,8,...,30.0,6.0,0.0,6.0,6.0,2019.0,0.0,2019.0,2019.0,4
15,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,22,8,...,31.0,3.0,NaN,3.0,3.0,2019.0,NaN,2019.0,2019.0,1
16,APAC,Australia,1,0,0,0,0,Bureaucratic_Code_5,4,4,...,30.0,9.0,0.0,9.0,9.0,2019.0,0.0,2019.0,2019.0,4
17,APAC,Australia,1,0,0,0,0,Bureaucratic_Code_5,4,4,...,30.0,9.0,0.0,9.0,9.0,2019.0,0.0,2019.0,2019.0,4
18,APAC,Australia,1,0,0,0,0,Bureaucratic_Code_5,20,2,...,30.0,9.0,0.0,9.0,9.0,2019.0,0.0,2019.0,2019.0,2
19,APAC,Australia,1,0,0,0,0,Bureaucratic_Code_5,22,8,...,30.0,9.0,0.0,9.0,9.0,2019.0,0.0,2019.0,2019.0,2
20,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,18,2,...,30.0,9.0,NaN,9.0,9.0,2019.0,NaN,2019.0,2019.0,1
21,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,18,2,...,31.0,12.0,NaN,12.0,12.0,2019.0,NaN,2019.0,2019.0,1
22,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,20,2,...,31.0,3.0,0.0,3.0,3.0,2019.0,0.0,2019.0,2019.0,9
23,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,20,2,...,31.0,12.0,0.0,12.0,12.0,2019.0,0.0,2019.0,2019.0,3
24,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,22,8,...,30.0,6.0,0.0,6.0,6.0,2019.0,0.0,2019.0,2019.0,3
25,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,28,7,...,31.0,12.0,NaN,12.0,12.0,2019.0,NaN,2019.0,2019.0,1
26,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,29,1,...,30.0,9.0,NaN,9.0,9.0,2019.0,NaN,2019.0,2019.0,1
27,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,29,1,...,31.0,12.0,NaN,12.0,12.0,2019.0,NaN,2019.0,2019.0,1
28,APAC,Australia,1,0,1,0,1,Bureaucratic_Code_5,22,8,...,30.0,6.0,0.0,6.0,6.0,2019.0,0.0,2019.0,2019.0,4
29,APAC,Australia,1,1,0,0,0,Bureaucratic_Code_4,4,4,...,31.0,12.0,0.0,12.0,12.0,2019.0,0.0,2019.0,2019.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1537,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,3,7,...,12.0,4.0,NaN,4.0,4.0,2019.0,NaN,2019.0,2019.0,1
1538,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,3,7,...,10.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1539,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,3,7,...,4.0,2.0,NaN,2.0,2.0,2019.0,NaN,2019.0,2019.0,1
1540,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,3,7,...,29.0,3.0,NaN,3.0,3.0,2019.0,NaN,2019.0,2019.0,1
1541,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,3,7,...,10.0,12.0,NaN,12.0,12.0,2019.0,NaN,2019.0,2019.0,1
1542,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,3,7,...,6.0,4.0,NaN,4.0,4.0,2020.0,NaN,2020.0,2020.0,1
1543,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,5,2,...,22.0,3.0,NaN,3.0,3.0,2019.0,NaN,2019.0,2019.0,1
1544,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,7,11,...,30.0,6.0,NaN,6.0,6.0,2020.0,NaN,2020.0,2020.0,1
1545,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,7,11,...,30.0,9.0,NaN,9.0,9.0,2020.0,NaN,2020.0,2020.0,1
1546,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,7,11,...,31.0,12.0,NaN,12.0,12.0,2020.0,NaN,2020.0,2020.0,1
1547,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,7,11,...,30.0,11.0,NaN,11.0,11.0,2020.0,NaN,2020.0,2020.0,1
1548,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,9,12,...,22.0,1.0,0.0,1.0,1.0,2019.0,0.0,2019.0,2019.0,2
1549,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,9,12,...,1.0,2.0,0.0,2.0,2.0,2019.0,0.0,2019.0,2019.0,2
1550,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,11,7,...,30.0,9.0,1.0,8.0,10.0,2019.0,0.0,2019.0,2019.0,3
1551,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,12,2,...,15.0,11.0,NaN,11.0,11.0,2019.0,NaN,2019.0,2019.0,1
1552,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,19,12,...,28.0,2.0,NaN,2.0,2.0,2020.0,NaN,2020.0,2020.0,1
1553,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,21,2,...,1.0,8.0,NaN,8.0,8.0,2019.0,NaN,2019.0,2019.0,1
1554,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,24,7,...,30.0,9.0,NaN,9.0,9.0,2019.0,NaN,2019.0,2019.0,1
1555,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,28,7,...,28.0,2.0,0.0,2.0,2.0,2019.0,0.0,2019.0,2019.0,2
1556,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,28,7,...,14.0,2.0,0.0,2.0,2.0,2019.0,0.0,2019.0,2019.0,2
1557,Middle East,Jordan,1,1,0,0,0,Bureaucratic_Code_4,17,3,...,15.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1558,Middle East,Jordan,1,1,1,1,0,Bureaucratic_Code_4,17,3,...,31.0,3.0,0.0,3.0,3.0,2019.0,0.0,2019.0,2019.0,4
1559,Middle East,Jordan,1,1,1,1,0,Bureaucratic_Code_4,17,3,...,31.0,3.0,NaN,3.0,3.0,2019.0,NaN,2019.0,2019.0,1
1560,Middle East,Jordan,1,1,1,1,0,Bureaucratic_Code_4,17,3,...,31.0,5.0,0.0,5.0,5.0,2019.0,0.0,2019.0,2019.0,2
1561,Middle East,Jordan,1,1,1,1,0,Bureaucratic_Code_4,19,2,...,30.0,4.0,NaN,4.0,4.0,2019.0,NaN,2019.0,2019.0,1
1562,Middle East,Jordan,1,1,1,1,0,Bureaucratic_Code_4,21,8,...,30.0,4.0,NaN,4.0,4.0,2019.0,NaN,2019.0,2019.0,1
1563,Middle East,KSA,1,1,0,0,0,Bureaucratic_Code_4,17,10,...,31.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1564,Middle East,KSA,1,1,1,1,0,Bureaucratic_Code_4,15,10,...,31.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1565,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,28,12,...,31.0,5.0,NaN,5.0,5.0,2019.0,NaN,2019.0,2019.0,1
1566,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,28,12,...,1.0,6.0,NaN,6.0,6.0,2019.0,NaN,2019.0,2019.0,1

In [202]:
train_agrupado = df_train_encodeado.groupby([
'Region',
'Territory',
'Pricing, Delivery_Terms_Quote_Appr',
'Pricing, Delivery_Terms_Approved',
'Bureaucratic_Code_0_Approval',
'Bureaucratic_Code_0_Approved',
'Submitted_for_Approval',
'Bureaucratic_Code',
#'Account_Created_Date',
'Account_Created_Date_Day',
'Account_Created_Date_Month',
'Account_Created_Date_Year',
'Source ',
'Billing_Country',
'Account_Name',
'Opportunity_Name',
'Opportunity_ID',
'Sales_Contract_No',
'Account_Owner',
'Opportunity_Owner',
'Account_Type',
'Opportunity_Type',
'Quote_Type',
'Delivery_Terms',
#'Opportunity_Created_Date',
'Opportunity_Created_Date_Day', 
'Opportunity_Created_Date_Month',
'Opportunity_Created_Date_Year', 
'Brand',
'Product_Type',
'Size',
'Product_Category_B',
'Price',
'Currency',
#'Last_Modified_Date',
'Last_Modified_Date_Day', 
'Last_Modified_Date_Month',
'Last_Modified_Date_Year', 
'Last_Modified_By',    
'Total_Amount_Currency',
'Total_Taxable_Amount_Currency',
'Total_Taxable_Amount',
'Stage',  
'Prod_Category_A'
    
]).agg(
                                  {'TRF': ['mean','std','min','max'], 
                                   'Total_Amount': ['mean','std','min','max'],
                                   
                                   #'Last_Activity':['min','max'],#esta columna tiene todos valores null 
                                                                 #ver si conviene sacarla        

                                   'Last_Activity_Day': ['mean','std','min','max'],
                                   'Last_Activity_Month': ['mean','std','min','max'], 
                                   'Last_Activity_Year': ['mean','std','min','max'], 
                                   
                                   #'Quote_Expiry_Date':['min','max'],
                                   'Quote_Expiry_Date_Day': ['mean','std','min','max'],
                                   'Quote_Expiry_Date_Month': ['mean','std','min','max'], 
                                   'Quote_Expiry_Date_Year': ['mean','std','min','max'],
                                   
                                   #'Product_Family':?,
                                   #'Product_Name':?,
                                   'Bit_Product_Family_0': ['mean','std','min','max'], 
                                   'Bit_Product_Family_1': ['mean','std','min','max'],
                                   'Bit_Product_Family_2': ['mean','std','min','max'], 
                                   'Bit_Product_Family_3': ['mean','std','min','max'], 
                                   'Bit_Product_Family_4': ['mean','std','min','max'],
                                   'Bit_Product_Family_5': ['mean','std','min','max'], 
                                   'Bit_Product_Family_6': ['mean','std','min','max'], 
                                   'Bit_Product_Family_7': ['mean','std','min','max'],
                                   'Bit_Product_Family_8': ['mean','std','min','max'],
                                   
                                   'Bit_Product_Name_0': ['mean','std','min','max'], 
                                   'Bit_Product_Name_1': ['mean','std','min','max'], 
                                   'Bit_Product_Name_2': ['mean','std','min','max'],
                                   'Bit_Product_Name_3': ['mean','std','min','max'], 
                                   'Bit_Product_Name_4': ['mean','std','min','max'], 
                                   'Bit_Product_Name_5': ['mean','std','min','max'],
                                   'Bit_Product_Name_6': ['mean','std','min','max'], 
                                   'Bit_Product_Name_7': ['mean','std','min','max'], 
                                   'Bit_Product_Name_8': ['mean','std','min','max'],
                                   'Bit_Product_Name_9': ['mean','std','min','max'],
                                   
                                   'ASP':['mean','std','min','max'],
                                   'ASP_Currency':'max',
                                   'ASP_(converted)': ['mean','std','min','max'],
                                   'ASP_(converted)_Currency':'max',
                                   
                                   'Delivery_Quarter':['mean','std','min','max'],
                                   'Delivery_Year':['mean','std','min','max'],
                                   'Delivery_Month':['mean','std','min','max'],

                                   #'Actual_Delivery_Date':['min','max'],#esta columna tienen todos valores null 
                                                                         #ver si conviene sacarla
                                   'Actual_Delivery_Date_Day':['mean','std','min','max'],
                                   'Actual_Delivery_Date_Month': ['mean','std','min','max'],
                                   'Actual_Delivery_Date_Year':['mean','std','min','max'],
                                   
                                   #'Planned_Delivery_Start_Date':['min','max'],
                                   'Planned_Delivery_Start_Date_Day':['mean','std','min','max'],
                                   'Planned_Delivery_Start_Date_Month':['mean','std','min','max'], 
                                   'Planned_Delivery_Start_Date_Year':['mean','std','min','max'],
                                   #'Planned_Delivery_End_Date':['min','max'],
                                   'Planned_Delivery_End_Date_Day':['mean','std','min','max'], 
                                   'Planned_Delivery_End_Date_Month':['mean','std','min','max'],
                                   'Planned_Delivery_End_Date_Year':['mean','std','min','max'],    
                                   'Opportunity_ID':'count' #cantidad de items por oportunidad
                                  })#.reset_index()

#lo que quiero es agrupar por opportunity_ID y categoricos iguales y promediar los numericos

#df_train.dtypes
#transformo los multiindices en un indice de un solo nivel
train_level0=train_agrupado.columns.get_level_values(0)
train_level1=train_agrupado.columns.get_level_values(1)
train_agrupado.columns=train_level0+'_'+train_level1
train_agrupado.reset_index(inplace=True)
train_agrupado.rename(columns={'Opportunity_ID_count':'Items_by_opportunity'},inplace=True)
train_agrupado.rename(columns={'ASP_Currency_max':'ASP_Currency'},inplace=True)
train_agrupado.rename(columns={'ASP_(converted)_Currency_max':'ASP_(converted)_Currency'},inplace=True)

train_agrupado

,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date_Day,Account_Created_Date_Month,...,Planned_Delivery_End_Date_Day_max,Planned_Delivery_End_Date_Month_mean,Planned_Delivery_End_Date_Month_std,Planned_Delivery_End_Date_Month_min,Planned_Delivery_End_Date_Month_max,Planned_Delivery_End_Date_Year_mean,Planned_Delivery_End_Date_Year_std,Planned_Delivery_End_Date_Year_min,Planned_Delivery_End_Date_Year_max,Items_by_opportunity
0,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,30.0,11.0,NaN,11.0,11.0,2017.0,NaN,2017.0,2017.0,1
1,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,15.0,12.0,NaN,12.0,12.0,2017.0,NaN,2017.0,2017.0,1
2,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,30.0,11.0,NaN,11.0,11.0,2017.0,NaN,2017.0,2017.0,1
3,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,1,3,...,30.0,6.0,NaN,6.0,6.0,2017.0,NaN,2017.0,2017.0,1
4,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,19,9,...,29.0,12.0,NaN,12.0,12.0,2017.0,NaN,2017.0,2017.0,1
5,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,19,9,...,29.0,12.0,0.0,12.0,12.0,2017.0,0.0,2017.0,2017.0,2
6,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,19,9,...,23.0,6.0,NaN,6.0,6.0,2016.0,NaN,2016.0,2016.0,1
7,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,20,2,...,29.0,6.5,1.0,6.0,8.0,2018.0,0.0,2018.0,2018.0,4
8,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,20,2,...,31.0,10.0,0.0,10.0,10.0,2018.0,0.0,2018.0,2018.0,5
9,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,20,2,...,31.0,12.0,0.0,12.0,12.0,2018.0,0.0,2018.0,2018.0,3
10,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,22,11,...,29.0,12.0,0.0,12.0,12.0,2017.0,0.0,2017.0,2017.0,2
11,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,22,11,...,1.0,12.0,NaN,12.0,12.0,2017.0,NaN,2017.0,2017.0,1
12,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,28,7,...,30.0,4.0,0.0,4.0,4.0,2018.0,0.0,2018.0,2018.0,5
13,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,28,7,...,29.0,6.0,0.0,6.0,6.0,2018.0,0.0,2018.0,2018.0,8
14,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,28,7,...,29.0,12.0,NaN,12.0,12.0,2017.0,NaN,2017.0,2017.0,1
15,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,1,3,...,29.0,9.0,NaN,9.0,9.0,2017.0,NaN,2017.0,2017.0,1
16,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
17,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,1,3,...,29.0,9.0,NaN,9.0,9.0,2017.0,NaN,2017.0,2017.0,1
18,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,1,3,...,30.0,11.0,NaN,11.0,11.0,2017.0,NaN,2017.0,2017.0,1
19,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,3,10,...,13.0,3.0,NaN,3.0,3.0,2017.0,NaN,2017.0,2017.0,1
20,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,3,10,...,11.0,9.0,NaN,9.0,9.0,2017.0,NaN,2017.0,2017.0,1
21,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,19,9,...,29.0,12.0,0.0,12.0,12.0,2017.0,0.0,2017.0,2017.0,3
22,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,19,9,...,31.0,12.0,0.0,12.0,12.0,2017.0,0.0,2017.0,2017.0,5
23,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,19,9,...,1.0,12.0,0.0,12.0,12.0,2017.0,0.0,2017.0,2017.0,5
24,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,19,9,...,11.0,12.0,0.0,12.0,12.0,2017.0,0.0,2017.0,2017.0,8
25,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,19,9,...,30.0,3.0,0.0,3.0,3.0,2018.0,0.0,2018.0,2018.0,14
26,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,19,9,...,29.0,6.0,0.0,6.0,6.0,2018.0,0.0,2018.0,2018.0,13
27,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,19,9,...,24.0,11.0,0.0,11.0,11.0,2017.0,0.0,2017.0,2017.0,7
28,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,19,9,...,1.0,12.0,0.0,12.0,12.0,2017.0,0.0,2017.0,2017.0,4
29,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,19,9,...,8.0,12.0,0.0,12.0,12.0,2017.0,0.0,2017.0,2017.0,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9811,Middle East,Oman,1,1,1,1,0,Bureaucratic_Code_4,17,5,...,31.0,3.0,NaN,3.0,3.0,2018.0,NaN,2018.0,2018.0,1
9812,Middle East,Pakistan,1,0,1,0,0,Bureaucratic_Code_5,7,5,...,31.0,8.0,NaN,8.0,8.0,2018.0,NaN,2018.0,2018.0,1
9813,Middle East,Pakistan,1,0,1,0,0,Bureaucratic_Code_5,7,5,...,31.0,7.0,0.0,7.0,7.0,2018.0,0.0,2018.0,2018.0,3
9814,Middle East,Pakistan,1,0,1,1,0,Bureaucratic_Code_5,7,5,...,15.0,10.0,NaN,10.0,10.0,2017.0,NaN,2017.0,2017.0,1
9815,Middle East,Pakistan,1,1,1,1,0,Bureaucratic_Code_4,7,5,...,31.0,5.0,NaN,5.0,5.0,2018.0,NaN,2018.0,2018.0,1
9816,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,13,10,...,31.0,12.0,NaN,12.0,12.0,2016.0,NaN,2016.0,2016.0,1
9817,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,15,10,...,28.0,2.0,NaN,2.0,2.0,2019.0,NaN,2019.0,2019.0,1
9818,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,15,10,...,1.0,3.0,NaN,3.0,3.0,2019.0,NaN,2019.0,2019.0,1
9819,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,17,10,...,28.0,2.0,0.0,2.0,2.0,2019.0,0.0,2019.0,2019.0,3
9820,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,3,7,...,30.0,1.0,NaN,1.0,1.0,2019.0,NaN,2019.0,2019.0,1
9821,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,7,6,...,1.0,8.0,NaN,8.0,8.0,2017.0,NaN,2017.0,2017.0,1
9822,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,10,2,...,31.0,7.0,NaN,7.0,7.0,2017.0,NaN,2017.0,2017.0,1
9823,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,13,11,...,1.0,4.0,NaN,4.0,4.0,2019.0,NaN,2019.0,2019.0,1
9824,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,15,12,...,1.0,7.0,NaN,7.0,7.0,2017.0,NaN,2017.0,2017.0,1
9825,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,16,3,...,15.0,6.0,NaN,6.0,6.0,2017.0,NaN,2017.0,2017.0,1
9826,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,16,11,...,30.0,10.0,NaN,10.0,10.0,2017.0,NaN,2017.0,2017.0,1
9827,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,16,11,...,31.0,7.0,NaN,7.0,7.0,2017.0,NaN,2017.0,2017.0,1
9828,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,16,11,...,15.0,12.0,NaN,12.0,12.0,2016.0,NaN,2016.0,2016.0,1
9829,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,17,5,...,31.0,7.0,NaN,7.0,7.0,2017.0,NaN,2017.0,2017.0,1
9830,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,18,10,...,31.0,1.0,NaN,1.0,1.0,2017.0,NaN,2017.0,2017.0,1
9831,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,18,10,...,28.0,2.0,NaN,2.0,2.0,2017.0,NaN,2017.0,2017.0,1
9832,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,19,6,...,31.0,3.0,NaN,3.0,3.0,2018.0,NaN,2018.0,2018.0,1
9833,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,21,2,...,1.0,8.0,NaN,8.0,8.0,2018.0,NaN,2018.0,2018.0,1
9834,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,24,1,...,31.0,3.0,NaN,3.0,3.0,2018.0,NaN,2018.0,2018.0,1
9835,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,24,1,...,30.0,8.0,NaN,8.0,8.0,2017.0,NaN,2017.0,2017.0,1
9836,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,24,1,...,28.0,2.0,NaN,2.0,2.0,2017.0,NaN,2017.0,2017.0,1
9837,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,28,10,...,15.0,12.0,NaN,12.0,12.0,2018.0,NaN,2018.0,2018.0,1
9838,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,28,10,...,1.0,4.0,NaN,4.0,4.0,2019.0,NaN,2019.0,2019.0,1
9839,Middle East,UAE (Others),1,1,1,1,0,Bureaucratic_Code_1,3,7,...,31.0,8.0,NaN,8.0,8.0,2018.0,NaN,2018.0,2018.0,1
9840,Middle East,UAE (Others),1,1,1,1,0,Bureaucratic_Code_4,13,10,...,23.0,12.0,NaN,12.0,12.0,2016.0,NaN,2016.0,2016.0,1

In [203]:
#genero el CSV
test_agrupado.to_csv(r'C:\Users\licha\Test_Preprocesado_TP2_Datos_2020-2C.csv',index=False , header=True)
train_agrupado.to_csv(r'C:\Users\licha\Train_Preprocesado_TP2_Datos_2020-2C.csv',index=False , header=True)

### Chequeo de dimensiones del set de datos luego de procesarlo

In [204]:
print ("dimensiones del set de test antes de procesarlo:",df_test.shape)
print ("dimensiones del set de test despues de procesarlo:",test_agrupado.shape)

dimensiones del set de test antes de procesarlo: (2551, 76)
dimensiones del set de test despues de procesarlo: (1567, 199)

In [205]:
print ("dimensiones del set de test antes de procesarlo:",df_train.shape)
print ("dimensiones del set de test despues de procesarlo:",train_agrupado.shape)

dimensiones del set de test antes de procesarlo: (16947, 77)
dimensiones del set de test despues de procesarlo: (9841, 208)