In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.legend import Legend
import matplotlib.patches as mpatches
import seaborn as sns
#from statsmodels.graphics.mosaicplot import mosaic
import io
import requests

## Lectura de los archivos de test y train

In [43]:
url_test="https://raw.githubusercontent.com/joacols/TP_orga_de_datos/main/Test_TP2_Datos_2020-2C.csv"
s_test=requests.get(url_test).content
df_test=pd.read_csv(io.StringIO(s_test.decode('utf-8')),

#df = pd.read_csv('Entrenamieto_ECI_2020.csv',
dtype={
'ID': np.int64,
'Pricing, Delivery_Terms_Quote_Approval': np.int64,
'Pricing, Delivery_Terms_Approved': np.int64,
'Bureaucratic_Code_0_Approval': np.int64,
'Bureaucratic_Code_0_Approved': np.int64,
'Submitted_for_Approval': np.int64,
'Opportunity_ID': np.int64,
#'Sales_Contract_No': np.int64,
'Delivery_Year': np.int64,
'Total_Power': np.int64,
#'Price':np.float64,
'ASP':np.float64,
'ASP_(converted)':np.float64,
'Total_Amount':np.float64},
parse_dates=[
'Account_Created_Date',
'Planned_Delivery_Start_Date',
'Planned_Delivery_End_Date',
'Opportunity_Created_Date',
'Last_Activity',
'Quote_Expiry_Date',
'Actual_Delivery_Date',
'Last_Modified_Date'
])

df_test.head()

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Month,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Prod_Category_A
0,6140,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 5,Q2,2019,NaT,0,EUR,162240.0,EUR,367419.0,Prod_Category_A_None
1,6146,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 5,Q2,2019,NaT,0,EUR,78624.0,EUR,367419.0,Prod_Category_A_None
2,6151,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 5,Q2,2019,NaT,0,EUR,126555.0,EUR,367419.0,Prod_Category_A_None
3,6118,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 6,Q2,2019,NaT,1,EUR,243360.0,EUR,757783.5,Prod_Category_A_None
4,6124,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,2019 - 6,Q2,2019,NaT,0,EUR,157248.0,EUR,757783.5,Prod_Category_A_None

In [44]:
url_train="https://raw.githubusercontent.com/joacols/TP_orga_de_datos/main/Train_TP2_Datos_2020-2C.csv"
s_train=requests.get(url_train).content
df_train=pd.read_csv(io.StringIO(s_train.decode('utf-8')),

#df = pd.read_csv('Entrenamieto_ECI_2020.csv',
dtype={
'ID': np.int64,
'Pricing, Delivery_Terms_Quote_Approval': np.int64,
'Pricing, Delivery_Terms_Approved': np.int64,
'Bureaucratic_Code_0_Approval': np.int64,
'Bureaucratic_Code_0_Approved': np.int64,
'Submitted_for_Approval': np.int64,
'Opportunity_ID': np.int64,
#'Sales_Contract_No': np.int64,
'Delivery_Year': np.int64,
'Total_Power': np.int64,
#'Price':np.float64,
'ASP':np.float64,
'ASP_(converted)':np.float64,
'Total_Amount':np.float64},
parse_dates=[
'Account_Created_Date',
'Planned_Delivery_Start_Date',
'Planned_Delivery_End_Date',
'Opportunity_Created_Date',
'Last_Activity',
'Quote_Expiry_Date',
'Actual_Delivery_Date',
'Last_Modified_Date'
])

df_train.head()

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Delivery_Quarter,Delivery_Year,Actual_Delivery_Date,TRF,Total_Amount_Currency,Total_Amount,Total_Taxable_Amount_Currency,Total_Taxable_Amount,Stage,Prod_Category_A
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,Q2,2016,NaT,10,EUR,5272800.0,EUR,5272800.0,Closed Lost,Prod_Category_A_None
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,Q1,2016,NaT,0,EUR,48230.0,EUR,48230.0,Closed Won,Prod_Category_A_None
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,Q1,2016,NaT,0,USD,83865.6,USD,83865.6,Closed Won,Prod_Category_A_None
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,14,USD,7421881.5,USD,7421881.5,Closed Lost,Prod_Category_A_None
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,Q1,2018,NaT,25,USD,13357192.5,USD,13357192.5,Closed Lost,Prod_Category_A_None

## Chequeo de caracteristicas de los set de datos

### Chequeo de dimensiones del set de datos

In [45]:
df_test.shape

(2551, 51)

In [46]:
df_train.shape

(16947, 52)

In [47]:
df_test['Opportunity_ID'].value_counts()

12266    26
10973    24
11089    18
11869    15
11248    11
11827    11
10804    11
11978    10
11280    10
11546    10
12080     9
11236     9
12265     9
12232     9
11830     9
11407     9
12276     9
12117     8
11408     8
10758     8
11870     8
11877     8
11861     8
10914     8
11296     8
11006     8
12286     8
11968     7
10796     7
11609     7
         ..
11402     1
12231     1
12229     1
11764     1
12225     1
11766     1
11768     1
12219     1
12217     1
12215     1
12213     1
11770     1
12209     1
12205     1
12175     1
12203     1
12201     1
12199     1
12197     1
12195     1
11772     1
12191     1
12189     1
11774     1
11776     1
11778     1
12181     1
12179     1
11518     1
11488     1
Name: Opportunity_ID, Length: 1567, dtype: int64

In [48]:
df_train['Opportunity_ID'].value_counts()

12460    36
2008     36
5123     26
6606     26
2911     24
767      18
6654     16
8698     16
6653     16
7568     16
6652     16
4568     16
7565     14
2653     14
6569     14
8293     14
7566     13
5890     13
7859     13
3580     13
1112     12
7604     12
7605     12
6614     12
6804     12
7592     11
6332     11
4288     11
7373     11
192      11
         ..
3416      1
5451      1
3288      1
1241      1
5339      1
3304      1
1257      1
7402      1
5355      1
9453      1
3320      1
1273      1
7418      1
3336      1
1289      1
7434      1
5387      1
9485      1
3352      1
1305      1
3368      1
5419      1
9517      1
3384      1
1337      1
7482      1
5435      1
3400      1
7498      1
0         1
Name: Opportunity_ID, Length: 9841, dtype: int64

In [49]:
#df_test.describe()

## CodificaciÃ³n de algunas variables categoricas

Cada oportunidad puede tener mÃ¡s de un item 
y en particular los items tienen dos variables categoricas que son el nombre y la familia.
Cuando agrupemos por oportunidad buscaremos valores representativos de todos los items asociados a esa oportunidad.
Generalmente aplicamos funciones numericas, motivo por el cual necesitaremos codificar estas dos variables categÃ³ricas como nÃºmeros.

In [51]:
import category_encoders as ce
encoder_family=ce.BinaryEncoder(cols=['Product_Family'])
df_train_bin1=encoder_family.fit_transform(df_train['Product_Family'])
df_train_bin1=df_train_bin1.add_prefix('Bit_')

encoder_name=ce.BinaryEncoder(cols=['Product_Name'])
df_train_bin2=encoder_name.fit_transform(df_train['Product_Name'])
df_train_bin2=df_train_bin2.add_prefix('Bit_')

df_train_encodeado=pd.concat([df_train,df_train_bin1,df_train_bin2],axis=1)
df_train_encodeado.head()

#from sklearn.preprocessing import LabelBinarizer
#lb = LabelBinarizer()
#df_train_bin=lb.fit_transform(df_train['Product_Family'])
#pd.concat([df_train,pd.DataFrame(df_train_bin)],axis=1)

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Bit_Product_Name_0,Bit_Product_Name_1,Bit_Product_Name_2,Bit_Product_Name_3,Bit_Product_Name_4,Bit_Product_Name_5,Bit_Product_Name_6,Bit_Product_Name_7,Bit_Product_Name_8,Bit_Product_Name_9
0,27761,EMEA,None,1,1,1,1,0,Bureaucratic_Code_4,2015-06-16,...,0,0,0,0,0,0,0,0,0,1
1,27760,EMEA,None,0,0,0,0,0,Bureaucratic_Code_4,2015-06-16,...,0,0,0,0,0,0,0,0,1,0
2,27446,Americas,NW America,0,0,0,0,0,Bureaucratic_Code_4,2015-04-21,...,0,0,0,0,0,0,0,0,1,1
3,16808,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,0,0,0,0,0,0,0,1,0,0
4,16805,Americas,NW America,1,0,1,0,0,Bureaucratic_Code_5,2013-07-27,...,0,0,0,0,0,0,0,1,0,0

In [52]:
df_test_bin1=encoder_family.fit_transform(df_test['Product_Family'])
df_test_bin1=df_test_bin1.add_prefix('Bit_')

df_test_bin2=encoder_name.fit_transform(df_test['Product_Name'])
df_test_bin2=df_test_bin2.add_prefix('Bit_')

df_test_encodeado=pd.concat([df_test,df_test_bin1,df_test_bin2],axis=1)
df_test_encodeado.head()

,ID,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,...,Bit_Product_Family_7,Bit_Product_Name_0,Bit_Product_Name_1,Bit_Product_Name_2,Bit_Product_Name_3,Bit_Product_Name_4,Bit_Product_Name_5,Bit_Product_Name_6,Bit_Product_Name_7,Bit_Product_Name_8
0,6140,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,0,0,0,0,0,0,0,0,1
1,6146,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,0,0,0,0,0,0,0,0,1,0
2,6151,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,0,0,0,0,0,0,0,1,1
3,6118,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,1,0,0,0,0,0,0,1,0,0
4,6124,EMEA,Germany,1,1,1,1,0,Bureaucratic_Code_4,2017-07-05,...,0,0,0,0,0,0,0,0,1,0

### Chequeo de nombres de columnas

In [53]:
df_test_encodeado.columns

Index(['ID', 'Region', 'Territory', 'Pricing, Delivery_Terms_Quote_Appr',
       'Pricing, Delivery_Terms_Approved', 'Bureaucratic_Code_0_Approval',
       'Bureaucratic_Code_0_Approved', 'Submitted_for_Approval',
       'Bureaucratic_Code', 'Account_Created_Date', 'Source ',
       'Billing_Country', 'Account_Name', 'Opportunity_Name', 'Opportunity_ID',
       'Sales_Contract_No', 'Account_Owner', 'Opportunity_Owner',
       'Account_Type', 'Opportunity_Type', 'Quote_Type', 'Delivery_Terms',
       'Opportunity_Created_Date', 'Brand', 'Product_Type', 'Size',
       'Product_Category_B', 'Price', 'Currency', 'Last_Activity',
       'Quote_Expiry_Date', 'Last_Modified_Date', 'Last_Modified_By',
       'Product_Family', 'Product_Name', 'ASP_Currency', 'ASP',
       'ASP_(converted)_Currency', 'ASP_(converted)',
       'Planned_Delivery_Start_Date', 'Planned_Delivery_End_Date', 'Month',
       'Delivery_Quarter', 'Delivery_Year', 'Actual_Delivery_Date', 'TRF',
       'Total_Amount_Currency', 'Total_Amount',
       'Total_Taxable_Amount_Currency', 'Total_Taxable_Amount',
       'Prod_Category_A', 'Bit_Product_Family_0', 'Bit_Product_Family_1',
       'Bit_Product_Family_2', 'Bit_Product_Family_3', 'Bit_Product_Family_4',
       'Bit_Product_Family_5', 'Bit_Product_Family_6', 'Bit_Product_Family_7',
       'Bit_Product_Name_0', 'Bit_Product_Name_1', 'Bit_Product_Name_2',
       'Bit_Product_Name_3', 'Bit_Product_Name_4', 'Bit_Product_Name_5',
       'Bit_Product_Name_6', 'Bit_Product_Name_7', 'Bit_Product_Name_8'],
      dtype='object')

In [54]:
df_train_encodeado.columns

Index(['ID', 'Region', 'Territory', 'Pricing, Delivery_Terms_Quote_Appr',
       'Pricing, Delivery_Terms_Approved', 'Bureaucratic_Code_0_Approval',
       'Bureaucratic_Code_0_Approved', 'Submitted_for_Approval',
       'Bureaucratic_Code', 'Account_Created_Date', 'Source ',
       'Billing_Country', 'Account_Name', 'Opportunity_Name', 'Opportunity_ID',
       'Sales_Contract_No', 'Account_Owner', 'Opportunity_Owner',
       'Account_Type', 'Opportunity_Type', 'Quote_Type', 'Delivery_Terms',
       'Opportunity_Created_Date', 'Brand', 'Product_Type', 'Size',
       'Product_Category_B', 'Price', 'Currency', 'Last_Activity',
       'Quote_Expiry_Date', 'Last_Modified_Date', 'Last_Modified_By',
       'Product_Family', 'Product_Name', 'ASP_Currency', 'ASP',
       'ASP_(converted)_Currency', 'ASP_(converted)',
       'Planned_Delivery_Start_Date', 'Planned_Delivery_End_Date', 'Month',
       'Delivery_Quarter', 'Delivery_Year', 'Actual_Delivery_Date', 'TRF',
       'Total_Amount_Currency', 'Total_Amount',
       'Total_Taxable_Amount_Currency', 'Total_Taxable_Amount', 'Stage',
       'Prod_Category_A', 'Bit_Product_Family_0', 'Bit_Product_Family_1',
       'Bit_Product_Family_2', 'Bit_Product_Family_3', 'Bit_Product_Family_4',
       'Bit_Product_Family_5', 'Bit_Product_Family_6', 'Bit_Product_Family_7',
       'Bit_Product_Family_8', 'Bit_Product_Name_0', 'Bit_Product_Name_1',
       'Bit_Product_Name_2', 'Bit_Product_Name_3', 'Bit_Product_Name_4',
       'Bit_Product_Name_5', 'Bit_Product_Name_6', 'Bit_Product_Name_7',
       'Bit_Product_Name_8', 'Bit_Product_Name_9'],
      dtype='object')

## Agrupamiento de los datos por Opportunity_ID

In [55]:
test_agrupado = df_test_encodeado.groupby([
'Region',
'Territory',
'Pricing, Delivery_Terms_Quote_Appr',
'Pricing, Delivery_Terms_Approved',
'Bureaucratic_Code_0_Approval',
'Bureaucratic_Code_0_Approved',
'Submitted_for_Approval',
'Bureaucratic_Code',
'Account_Created_Date',
'Source ',
'Billing_Country',
'Account_Name',
'Opportunity_Name',
'Opportunity_ID',
'Sales_Contract_No',
'Account_Owner',
'Opportunity_Owner',
'Account_Type',
'Opportunity_Type',
'Quote_Type',
'Delivery_Terms',
'Opportunity_Created_Date',
'Brand',
'Product_Type',
'Size',
'Product_Category_B',
'Price',
'Currency',
'Last_Modified_Date',
'Last_Modified_By',    
'Total_Amount_Currency',
'Total_Taxable_Amount_Currency',
'Total_Taxable_Amount',
#'Stage',  #test no tiene stage (que es la columna a predecir)
'Prod_Category_A'

]).agg(
                                  {'TRF': ['mean','std','min','max'], 
                                   'Total_Amount': ['mean','std','min','max'],
                                   
                                   'Last_Activity':['min','max'],#esta columna tiene todos valores null 
                                                                 #ver si conviene sacarla        
                                   'Quote_Expiry_Date':['min','max'],
                                   
                                   #'Product_Family':?,
                                   #'Product_Name':?,
                                   'Bit_Product_Family_0': ['mean','std','min','max'], 
                                   'Bit_Product_Family_1': ['mean','std','min','max'],
                                   'Bit_Product_Family_2': ['mean','std','min','max'], 
                                   'Bit_Product_Family_3': ['mean','std','min','max'], 
                                   'Bit_Product_Family_4': ['mean','std','min','max'],
                                   'Bit_Product_Family_5': ['mean','std','min','max'], 
                                   'Bit_Product_Family_6': ['mean','std','min','max'], 
                                   'Bit_Product_Family_7': ['mean','std','min','max'],
                                   
                                   'Bit_Product_Name_0': ['mean','std','min','max'], 
                                   'Bit_Product_Name_1': ['mean','std','min','max'], 
                                   'Bit_Product_Name_2': ['mean','std','min','max'],
                                   'Bit_Product_Name_3': ['mean','std','min','max'], 
                                   'Bit_Product_Name_4': ['mean','std','min','max'], 
                                   'Bit_Product_Name_5': ['mean','std','min','max'],
                                   'Bit_Product_Name_6': ['mean','std','min','max'], 
                                   'Bit_Product_Name_7': ['mean','std','min','max'], 
                                   'Bit_Product_Name_8': ['mean','std','min','max'],
                                   
                                   'ASP':['mean','std','min','max'],
                                   'ASP_Currency':'max',
                                   'ASP_(converted)': ['mean','std','min','max'],
                                   'ASP_(converted)_Currency':'max',
                                   
                                   'Delivery_Quarter':['min','max'],
                                   'Delivery_Year':['min','max'],
                                   'Actual_Delivery_Date':['min','max'],#esta columna tiene todos valores null 
                                                                        #ver si conviene sacarla
                                   
                                   'Planned_Delivery_Start_Date':['min','max'],
                                   'Planned_Delivery_End_Date':['min','max'],
                                   'Month':['min','max'],
                                   'Opportunity_ID':'count' #cantidad de items por oportunidad
                                  })#.reset_index()

#lo que quiero es agrupar por opportunity_ID y categoricos iguales y promediar los numericos

#df_train.dtypes
#transformo los multiindices en un indice de un solo nivel
test_level0=test_agrupado.columns.get_level_values(0)
test_level1=test_agrupado.columns.get_level_values(1)
test_agrupado.columns=test_level0+'_'+test_level1
test_agrupado.reset_index(inplace=True)
test_agrupado.rename(columns={'Opportunity_ID_count':'Items_by_opportunity'},inplace=True)
test_agrupado

,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,Source,...,Delivery_Year_max,Actual_Delivery_Date_min,Actual_Delivery_Date_max,Planned_Delivery_Start_Date_min,Planned_Delivery_Start_Date_max,Planned_Delivery_End_Date_min,Planned_Delivery_End_Date_max,Month_min,Month_max,Items_by_opportunity
0,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2017-02-20,Source_7,...,2019,NaT,NaT,2019-03-31,2019-03-31,2019-12-31,2019-12-31,2019 - 3,2019 - 3,2
1,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2018-08-22,Source_13,...,2019,NaT,NaT,2019-03-31,2019-03-31,2019-12-31,2019-12-31,2019 - 3,2019 - 3,1
2,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2018-08-22,Source_13,...,2019,NaT,NaT,2019-02-11,2019-02-11,2019-03-31,2019-03-31,2019 - 2,2019 - 2,8
3,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2017-02-20,Source_7,...,2019,NaT,NaT,2019-04-01,2019-04-01,2019-06-30,2019-06-30,2019 - 4,2019 - 4,2
4,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2017-02-20,Source_7,...,2019,NaT,NaT,2019-04-01,2019-04-01,2019-06-30,2019-06-30,2019 - 4,2019 - 4,7
5,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2017-02-20,Source_7,...,2019,NaT,NaT,2019-04-01,2019-04-01,2019-06-30,2019-06-30,2019 - 4,2019 - 4,4
6,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2017-02-20,Source_7,...,2019,NaT,NaT,2019-03-20,2019-03-20,2019-03-31,2019-03-31,2019 - 3,2019 - 3,2
7,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2017-02-20,Source_7,...,2019,NaT,NaT,2019-03-01,2019-03-01,2019-03-01,2019-03-31,2019 - 3,2019 - 3,2
8,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2017-02-20,Source_7,...,2019,NaT,NaT,2019-03-01,2019-03-01,2019-03-31,2019-03-31,2019 - 3,2019 - 3,1
9,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2018-08-22,Source_13,...,2019,NaT,NaT,2019-04-30,2019-04-30,2019-12-31,2019-12-31,2019 - 4,2019 - 4,4
10,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2018-08-22,Source_13,...,2019,NaT,NaT,2019-04-01,2019-04-01,2019-06-23,2019-06-30,2019 - 4,2019 - 4,4
11,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2018-08-22,Source_13,...,2019,NaT,NaT,2019-04-01,2019-04-01,2019-06-30,2019-06-30,2019 - 4,2019 - 4,4
12,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2018-08-22,Source_13,...,2019,NaT,NaT,2019-03-11,2019-03-11,2019-03-31,2019-03-31,2019 - 3,2019 - 3,1
13,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2019-03-22,Source_7,...,2019,NaT,NaT,2019-06-03,2019-06-03,2019-09-30,2019-09-30,2019 - 6,2019 - 6,2
14,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2019-04-04,Source_7,...,2019,NaT,NaT,2019-06-03,2019-06-03,2019-06-03,2019-06-28,2019 - 6,2019 - 6,9
15,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2019-04-04,Source_7,...,2019,NaT,NaT,2019-06-03,2019-06-03,2019-06-28,2019-06-28,2019 - 6,2019 - 6,6
16,APAC,Australia,1,0,0,0,0,Bureaucratic_Code_5,2017-02-20,Source_7,...,2019,NaT,NaT,2019-07-01,2019-07-01,2019-09-30,2019-09-30,2019 - 7,2019 - 7,2
17,APAC,Australia,1,0,0,0,0,Bureaucratic_Code_5,2018-08-22,Source_13,...,2019,NaT,NaT,2019-07-01,2019-07-01,2019-09-30,2019-09-30,2019 - 7,2019 - 7,2
18,APAC,Australia,1,0,0,0,0,Bureaucratic_Code_5,2019-04-04,Source_7,...,2019,NaT,NaT,2019-09-30,2019-09-30,2019-09-30,2019-09-30,2019 - 9,2019 - 9,4
19,APAC,Australia,1,0,0,0,0,Bureaucratic_Code_5,2019-04-04,Source_7,...,2019,NaT,NaT,2019-09-30,2019-09-30,2019-09-30,2019-09-30,2019 - 9,2019 - 9,4
20,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,2013-07-28,None,...,2019,NaT,NaT,2019-11-01,2019-11-01,2019-12-31,2019-12-31,2019 - 11,2019 - 11,1
21,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,2017-02-18,Source_7,...,2019,NaT,NaT,2019-07-01,2019-07-01,2019-09-30,2019-09-30,2019 - 7,2019 - 7,1
22,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,2017-02-18,Source_7,...,2019,NaT,NaT,2019-10-01,2019-10-01,2019-12-31,2019-12-31,2019 - 10,2019 - 10,1
23,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,2017-02-20,Source_7,...,2019,NaT,NaT,2019-02-11,2019-02-11,2019-03-31,2019-03-31,2019 - 2,2019 - 2,9
24,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,2017-02-20,Source_7,...,2019,NaT,NaT,2019-09-30,2019-09-30,2019-12-31,2019-12-31,2019 - 9,2019 - 9,3
25,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,2018-08-22,Source_13,...,2019,NaT,NaT,2019-04-01,2019-04-01,2019-06-30,2019-06-30,2019 - 4,2019 - 4,3
26,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,2019-01-29,Source_7,...,2019,NaT,NaT,2019-07-01,2019-07-01,2019-09-30,2019-09-30,2019 - 7,2019 - 7,1
27,APAC,Australia,1,0,1,0,0,Bureaucratic_Code_5,2019-01-29,Source_7,...,2019,NaT,NaT,2019-10-01,2019-10-01,2019-12-31,2019-12-31,2019 - 10,2019 - 10,1
28,APAC,Australia,1,0,1,0,1,Bureaucratic_Code_5,2018-08-22,Source_13,...,2019,NaT,NaT,2019-04-01,2019-04-01,2019-06-30,2019-06-30,2019 - 4,2019 - 4,4
29,APAC,Australia,1,1,0,0,0,Bureaucratic_Code_4,2017-02-20,Source_7,...,2019,NaT,NaT,2019-12-31,2019-12-31,2019-12-31,2019-12-31,2019 - 12,2019 - 12,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1537,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2013-11-07,Source_7,...,2020,NaT,NaT,2020-04-01,2020-04-01,2020-06-30,2020-06-30,2020 - 4,2020 - 4,1
1538,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2013-11-07,Source_7,...,2020,NaT,NaT,2020-07-01,2020-07-01,2020-09-30,2020-09-30,2020 - 7,2020 - 7,1
1539,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2013-11-07,Source_7,...,2020,NaT,NaT,2020-10-01,2020-10-01,2020-12-31,2020-12-31,2020 - 10,2020 - 10,1
1540,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2013-11-07,Source_7,...,2020,NaT,NaT,2020-11-01,2020-11-01,2020-11-30,2020-11-30,2020 - 11,2020 - 11,1
1541,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2014-07-24,Source_11,...,2019,NaT,NaT,2019-09-01,2019-09-01,2019-09-30,2019-09-30,2019 - 9,2019 - 9,1
1542,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2015-07-03,None,...,2019,NaT,NaT,2019-04-12,2019-04-12,2019-04-12,2019-04-12,2019 - 4,2019 - 4,1
1543,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2015-07-03,None,...,2019,NaT,NaT,2019-05-15,2019-05-15,2019-05-15,2019-05-15,2019 - 5,2019 - 5,1
1544,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2015-07-03,None,...,2019,NaT,NaT,2019-04-12,2019-04-12,2019-04-12,2019-04-12,2019 - 4,2019 - 4,1
1545,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2015-07-03,None,...,2019,NaT,NaT,2019-05-10,2019-05-10,2019-05-10,2019-05-10,2019 - 5,2019 - 5,1
1546,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2015-07-03,None,...,2019,NaT,NaT,2019-02-04,2019-02-04,2019-02-04,2019-02-04,2019 - 2,2019 - 2,1
1547,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2015-07-03,None,...,2019,NaT,NaT,2019-03-29,2019-03-29,2019-03-29,2019-03-29,2019 - 3,2019 - 3,1
1548,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2015-07-03,None,...,2019,NaT,NaT,2019-10-08,2019-10-08,2019-12-10,2019-12-10,2019 - 10,2019 - 10,1
1549,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2015-07-03,None,...,2020,NaT,NaT,2020-01-10,2020-01-10,2020-04-06,2020-04-06,2020 - 1,2020 - 1,1
1550,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2016-12-09,None,...,2019,NaT,NaT,2019-01-22,2019-01-22,2019-01-22,2019-01-22,2019 - 1,2019 - 1,2
1551,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2016-12-09,None,...,2019,NaT,NaT,2019-02-01,2019-02-01,2019-02-01,2019-02-01,2019 - 2,2019 - 2,2
1552,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2018-02-05,None,...,2019,NaT,NaT,2019-03-01,2019-03-01,2019-03-22,2019-03-22,2019 - 3,2019 - 3,1
1553,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2018-07-11,None,...,2019,NaT,NaT,2019-08-30,2019-10-25,2019-08-30,2019-10-25,2019 - 10,2019 - 9,3
1554,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2018-12-19,None,...,2019,NaT,NaT,2019-11-01,2019-11-01,2020-02-28,2020-02-28,2019 - 11,2019 - 11,1
1555,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2019-02-12,None,...,2019,NaT,NaT,2019-11-15,2019-11-15,2019-11-15,2019-11-15,2019 - 11,2019 - 11,1
1556,Japan,None,1,1,1,1,0,Bureaucratic_Code_4,2019-02-21,Source_7,...,2019,NaT,NaT,2019-08-01,2019-08-01,2019-08-01,2019-08-01,2019 - 8,2019 - 8,1
1557,Middle East,Jordan,1,1,0,0,0,Bureaucratic_Code_4,2016-03-17,Source_7,...,2019,NaT,NaT,2019-04-15,2019-04-15,2019-05-15,2019-05-15,2019 - 4,2019 - 4,1
1558,Middle East,Jordan,1,1,1,1,0,Bureaucratic_Code_4,2016-03-17,Source_7,...,2019,NaT,NaT,2019-02-28,2019-02-28,2019-03-31,2019-03-31,2019 - 2,2019 - 2,4
1559,Middle East,Jordan,1,1,1,1,0,Bureaucratic_Code_4,2016-03-17,Source_7,...,2019,NaT,NaT,2019-02-04,2019-02-04,2019-03-31,2019-03-31,2019 - 2,2019 - 2,1
1560,Middle East,Jordan,1,1,1,1,0,Bureaucratic_Code_4,2016-03-17,Source_7,...,2019,NaT,NaT,2019-04-01,2019-04-01,2019-05-31,2019-05-31,2019 - 4,2019 - 4,2
1561,Middle East,Jordan,1,1,1,1,0,Bureaucratic_Code_4,2017-08-21,Source_7,...,2019,NaT,NaT,2019-04-01,2019-04-01,2019-04-30,2019-04-30,2019 - 4,2019 - 4,1
1562,Middle East,Jordan,1,1,1,1,0,Bureaucratic_Code_4,2019-02-19,Source_13,...,2019,NaT,NaT,2019-04-01,2019-04-01,2019-04-30,2019-04-30,2019 - 4,2019 - 4,1
1563,Middle East,KSA,1,1,0,0,0,Bureaucratic_Code_4,2018-10-17,Source_7,...,2019,NaT,NaT,2019-04-30,2019-04-30,2019-05-31,2019-05-31,2019 - 4,2019 - 4,1
1564,Middle East,KSA,1,1,1,1,0,Bureaucratic_Code_4,2018-10-15,Source_13,...,2019,NaT,NaT,2019-03-31,2019-03-31,2019-05-31,2019-05-31,2019 - 3,2019 - 3,1
1565,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,2017-12-28,Source_7,...,2019,NaT,NaT,2019-04-20,2019-04-20,2019-05-31,2019-05-31,2019 - 4,2019 - 4,1
1566,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,2017-12-28,Source_7,...,2019,NaT,NaT,2019-03-01,2019-03-01,2019-06-01,2019-06-01,2019 - 3,2019 - 3,1

In [56]:
train_agrupado = df_train_encodeado.groupby([
'Region',
'Territory',
'Pricing, Delivery_Terms_Quote_Appr',
'Pricing, Delivery_Terms_Approved',
'Bureaucratic_Code_0_Approval',
'Bureaucratic_Code_0_Approved',
'Submitted_for_Approval',
'Bureaucratic_Code',
'Account_Created_Date',
'Source ',
'Billing_Country',
'Account_Name',
'Opportunity_Name',
'Opportunity_ID',
'Sales_Contract_No',
'Account_Owner',
'Opportunity_Owner',
'Account_Type',
'Opportunity_Type',
'Quote_Type',
'Delivery_Terms',
'Opportunity_Created_Date',
'Brand',
'Product_Type',
'Size',
'Product_Category_B',
'Price',
'Currency',
'Last_Modified_Date',
'Last_Modified_By',    
'Total_Amount_Currency',
'Total_Taxable_Amount_Currency',
'Total_Taxable_Amount',
'Stage',  
'Prod_Category_A'

]).agg(
                                  {'TRF': ['mean','std','min','max'], 
                                   'Total_Amount': ['mean','std','min','max'],
                                   
                                   'Last_Activity':['min','max'],#esta columna tiene todos valores null 
                                                                 #ver si conviene sacarla        
                                   'Quote_Expiry_Date':['min','max'],
                                   
                                   #'Product_Family':?,
                                   #'Product_Name':?,
                                   'Bit_Product_Family_0': ['mean','std','min','max'], 
                                   'Bit_Product_Family_1': ['mean','std','min','max'],
                                   'Bit_Product_Family_2': ['mean','std','min','max'], 
                                   'Bit_Product_Family_3': ['mean','std','min','max'], 
                                   'Bit_Product_Family_4': ['mean','std','min','max'],
                                   'Bit_Product_Family_5': ['mean','std','min','max'], 
                                   'Bit_Product_Family_6': ['mean','std','min','max'], 
                                   'Bit_Product_Family_7': ['mean','std','min','max'],
                                   'Bit_Product_Family_8': ['mean','std','min','max'],
                                   
                                   'Bit_Product_Name_0': ['mean','std','min','max'], 
                                   'Bit_Product_Name_1': ['mean','std','min','max'], 
                                   'Bit_Product_Name_2': ['mean','std','min','max'],
                                   'Bit_Product_Name_3': ['mean','std','min','max'], 
                                   'Bit_Product_Name_4': ['mean','std','min','max'], 
                                   'Bit_Product_Name_5': ['mean','std','min','max'],
                                   'Bit_Product_Name_6': ['mean','std','min','max'], 
                                   'Bit_Product_Name_7': ['mean','std','min','max'], 
                                   'Bit_Product_Name_8': ['mean','std','min','max'],
                                   'Bit_Product_Name_9': ['mean','std','min','max'],
                                   
                                   'ASP':['mean','std','min','max'],
                                   'ASP_Currency':'max',
                                   'ASP_(converted)': ['mean','std','min','max'],
                                   'ASP_(converted)_Currency':'max',
                                   
                                   'Delivery_Quarter':['min','max'],
                                   'Delivery_Year':['min','max'],
                                   'Actual_Delivery_Date':['min','max'],#esta columna tiene todos valores null 
                                                                        #ver si conviene sacarla
                                   
                                   'Planned_Delivery_Start_Date':['min','max'],
                                   'Planned_Delivery_End_Date':['min','max'],
                                   'Month':['min','max'],
                                   'Opportunity_ID':'count' #cantidad de items por oportunidad
                                  })#.reset_index()

#lo que quiero es agrupar por opportunity_ID y categoricos iguales y promediar los numericos

#df_train.dtypes
#transformo los multiindices en un indice de un solo nivel
train_level0=train_agrupado.columns.get_level_values(0)
train_level1=train_agrupado.columns.get_level_values(1)
train_agrupado.columns=train_level0+'_'+train_level1
train_agrupado.reset_index(inplace=True)
train_agrupado.rename(columns={'Opportunity_ID_count':'Items_by_opportunity'},inplace=True)
train_agrupado

,Region,Territory,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Bureaucratic_Code,Account_Created_Date,Source,...,Delivery_Year_max,Actual_Delivery_Date_min,Actual_Delivery_Date_max,Planned_Delivery_Start_Date_min,Planned_Delivery_Start_Date_max,Planned_Delivery_End_Date_min,Planned_Delivery_End_Date_max,Month_min,Month_max,Items_by_opportunity
0,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2013-07-28,None,...,2018,NaT,NaT,2018-04-02,2018-04-02,2018-04-30,2018-04-30,2018 - 4,2018 - 4,5
1,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2013-07-28,None,...,2018,NaT,NaT,2018-06-01,2018-06-01,2018-06-29,2018-06-29,2018 - 6,2018 - 6,8
2,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2013-07-28,None,...,2017,NaT,NaT,2017-12-18,2017-12-18,2017-12-29,2017-12-29,2017 - 12,2017 - 12,1
3,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2014-09-19,Source_9,...,2017,NaT,NaT,2017-12-21,2017-12-21,2017-12-29,2017-12-29,2017 - 12,2017 - 12,1
4,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2014-09-19,Source_9,...,2017,NaT,NaT,2017-12-21,2017-12-21,2017-12-29,2017-12-29,2017 - 12,2017 - 12,2
5,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2014-09-19,Source_9,...,2016,NaT,NaT,2016-04-01,2016-04-01,2016-06-23,2016-06-23,2016 - 4,2016 - 4,1
6,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2017-02-20,Source_7,...,2018,NaT,NaT,2018-06-01,2018-07-31,2018-06-29,2018-08-18,2018 - 6,2018 - 7,4
7,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2017-02-20,Source_7,...,2018,NaT,NaT,2018-10-01,2018-10-01,2018-10-31,2018-10-31,2018 - 10,2018 - 10,5
8,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2017-02-20,Source_7,...,2018,NaT,NaT,2018-11-01,2018-11-01,2018-12-31,2018-12-31,2018 - 11,2018 - 11,3
9,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2017-03-01,Source_7,...,2017,NaT,NaT,2017-10-02,2017-10-02,2017-11-30,2017-11-30,2017 - 10,2017 - 10,1
10,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2017-03-01,Source_7,...,2017,NaT,NaT,2017-10-13,2017-10-13,2017-12-15,2017-12-15,2017 - 10,2017 - 10,1
11,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2017-03-01,Source_7,...,2017,NaT,NaT,2017-10-02,2017-10-02,2017-11-30,2017-11-30,2017 - 10,2017 - 10,1
12,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2017-03-01,Source_7,...,2017,NaT,NaT,2017-06-01,2017-06-01,2017-06-30,2017-06-30,2017 - 6,2017 - 6,1
13,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2017-11-22,Source_9,...,2017,NaT,NaT,2017-12-21,2017-12-21,2017-12-29,2017-12-29,2017 - 12,2017 - 12,2
14,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_1,2017-11-22,Source_9,...,2017,NaT,NaT,2017-11-22,2017-11-22,2017-12-01,2017-12-01,2017 - 11,2017 - 11,1
15,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2013-07-28,None,...,2019,NaT,NaT,2019-02-01,2019-02-01,2019-03-31,2019-03-31,2019 - 2,2019 - 2,4
16,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2013-07-28,None,...,2017,NaT,NaT,2017-12-25,2017-12-25,2017-12-29,2017-12-29,2017 - 12,2017 - 12,2
17,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2013-07-28,None,...,2018,NaT,NaT,2018-01-25,2018-02-01,2018-03-30,2018-03-30,2018 - 1,2018 - 2,10
18,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2013-07-28,None,...,2018,NaT,NaT,2018-03-31,2018-04-02,2018-06-22,2018-06-29,2018 - 3,2018 - 4,16
19,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2013-07-28,None,...,2018,NaT,NaT,2018-01-01,2018-01-01,2018-01-31,2018-01-31,2018 - 1,2018 - 1,3
20,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2013-07-28,None,...,2017,NaT,NaT,2017-12-29,2017-12-29,2018-01-31,2018-01-31,2017 - 12,2017 - 12,2
21,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2013-07-28,None,...,2018,NaT,NaT,2018-06-01,2018-06-01,2018-06-29,2018-06-29,2018 - 6,2018 - 6,8
22,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2013-07-28,None,...,2017,NaT,NaT,2017-12-19,2017-12-19,2017-12-29,2017-12-29,2017 - 12,2017 - 12,3
23,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2013-10-03,None,...,2017,NaT,NaT,2017-02-20,2017-02-20,2017-03-13,2017-03-13,2017 - 2,2017 - 2,1
24,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2013-10-03,None,...,2017,NaT,NaT,2017-08-31,2017-08-31,2017-09-11,2017-09-11,2017 - 8,2017 - 8,1
25,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2014-09-19,Source_9,...,2017,NaT,NaT,2017-12-19,2017-12-19,2017-12-29,2017-12-29,2017 - 12,2017 - 12,3
26,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2014-09-19,Source_9,...,2017,NaT,NaT,2017-11-21,2017-11-21,2017-12-31,2017-12-31,2017 - 11,2017 - 11,5
27,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2014-09-19,Source_9,...,2017,NaT,NaT,2017-11-20,2017-11-20,2017-12-01,2017-12-01,2017 - 11,2017 - 11,5
28,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2014-09-19,Source_9,...,2017,NaT,NaT,2017-11-20,2017-11-27,2017-12-11,2017-12-11,2017 - 11,2017 - 11,8
29,APAC,Australia,0,0,0,0,0,Bureaucratic_Code_4,2014-09-19,Source_9,...,2018,NaT,NaT,2018-02-01,2018-02-01,2018-03-30,2018-03-30,2018 - 2,2018 - 2,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9811,Middle East,Oman,1,1,1,1,0,Bureaucratic_Code_4,2018-11-14,Source_13,...,2019,NaT,NaT,2019-03-01,2019-03-01,2019-05-01,2019-05-01,2019 - 3,2019 - 3,1
9812,Middle East,Pakistan,1,0,1,0,0,Bureaucratic_Code_5,2017-05-07,None,...,2018,NaT,NaT,2018-08-01,2018-08-01,2018-08-31,2018-08-31,2018 - 8,2018 - 8,1
9813,Middle East,Pakistan,1,0,1,0,0,Bureaucratic_Code_5,2017-05-07,None,...,2018,NaT,NaT,2018-06-30,2018-06-30,2018-07-31,2018-07-31,2018 - 6,2018 - 6,3
9814,Middle East,Pakistan,1,0,1,1,0,Bureaucratic_Code_5,2017-05-07,None,...,2017,NaT,NaT,2017-08-15,2017-08-15,2017-10-15,2017-10-15,2017 - 8,2017 - 8,1
9815,Middle East,Pakistan,1,1,1,1,0,Bureaucratic_Code_4,2017-05-07,None,...,2018,NaT,NaT,2018-04-01,2018-04-01,2018-05-31,2018-05-31,2018 - 4,2018 - 4,1
9816,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,2016-10-13,Source_7,...,2016,NaT,NaT,2016-11-20,2016-11-20,2016-12-31,2016-12-31,2016 - 11,2016 - 11,1
9817,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,2018-10-15,Source_13,...,2019,NaT,NaT,2019-01-01,2019-01-01,2019-02-28,2019-02-28,2019 - 1,2019 - 1,1
9818,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,2018-10-15,Source_13,...,2019,NaT,NaT,2019-01-01,2019-01-01,2019-03-01,2019-03-01,2019 - 1,2019 - 1,1
9819,Middle East,Saudi Arabia,1,1,1,1,0,Bureaucratic_Code_4,2018-10-17,Source_7,...,2019,NaT,NaT,2019-01-01,2019-01-01,2019-02-28,2019-02-28,2019 - 1,2019 - 1,3
9820,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2015-02-10,None,...,2017,NaT,NaT,2017-07-01,2017-07-01,2017-07-31,2017-07-31,2017 - 7,2017 - 7,1
9821,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2016-10-18,None,...,2016,NaT,NaT,2016-12-11,2016-12-11,2017-01-31,2017-01-31,2016 - 12,2016 - 12,1
9822,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2016-10-18,None,...,2016,NaT,NaT,2016-12-27,2016-12-27,2017-02-28,2017-02-28,2016 - 12,2016 - 12,1
9823,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2016-11-16,None,...,2017,NaT,NaT,2017-09-01,2017-09-01,2017-10-30,2017-10-30,2017 - 9,2017 - 9,1
9824,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2016-11-16,None,...,2017,NaT,NaT,2017-07-01,2017-07-01,2017-07-31,2017-07-31,2017 - 7,2017 - 7,1
9825,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2016-11-16,None,...,2016,NaT,NaT,2016-11-29,2016-11-29,2016-12-15,2016-12-15,2016 - 11,2016 - 11,1
9826,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2016-12-15,None,...,2017,NaT,NaT,2017-06-01,2017-06-01,2017-07-01,2017-07-01,2017 - 6,2017 - 6,1
9827,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2017-01-24,None,...,2018,NaT,NaT,2018-02-01,2018-02-01,2018-03-31,2018-03-31,2018 - 2,2018 - 2,1
9828,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2017-01-24,None,...,2017,NaT,NaT,2017-07-15,2017-07-15,2017-08-30,2017-08-30,2017 - 7,2017 - 7,1
9829,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2017-01-24,None,...,2017,NaT,NaT,2017-01-26,2017-01-26,2017-02-28,2017-02-28,2017 - 1,2017 - 1,1
9830,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2017-02-21,None,...,2018,NaT,NaT,2018-03-01,2018-03-01,2018-08-01,2018-08-01,2018 - 3,2018 - 3,1
9831,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2017-03-16,None,...,2017,NaT,NaT,2017-05-15,2017-05-15,2017-06-15,2017-06-15,2017 - 5,2017 - 5,1
9832,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2017-05-17,None,...,2017,NaT,NaT,2017-06-30,2017-06-30,2017-07-31,2017-07-31,2017 - 6,2017 - 6,1
9833,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2017-06-07,Source_13,...,2017,NaT,NaT,2017-07-01,2017-07-01,2017-08-01,2017-08-01,2017 - 7,2017 - 7,1
9834,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2017-06-19,Source_7,...,2018,NaT,NaT,2018-02-01,2018-02-01,2018-03-31,2018-03-31,2018 - 2,2018 - 2,1
9835,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2018-07-03,Source_3,...,2019,NaT,NaT,2019-01-07,2019-01-07,2019-01-30,2019-01-30,2019 - 1,2019 - 1,1
9836,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2018-10-28,None,...,2018,NaT,NaT,2018-11-15,2018-11-15,2018-12-15,2018-12-15,2018 - 11,2018 - 11,1
9837,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2018-10-28,None,...,2019,NaT,NaT,2019-02-01,2019-02-01,2019-04-01,2019-04-01,2019 - 2,2019 - 2,1
9838,Middle East,UAE (Dubai),1,1,1,1,0,Bureaucratic_Code_4,2018-11-13,None,...,2019,NaT,NaT,2019-02-01,2019-02-01,2019-04-01,2019-04-01,2019 - 2,2019 - 2,1
9839,Middle East,UAE (Others),1,1,1,1,0,Bureaucratic_Code_1,2018-07-03,Source_3,...,2018,NaT,NaT,2018-07-15,2018-07-15,2018-08-31,2018-08-31,2018 - 7,2018 - 7,1
9840,Middle East,UAE (Others),1,1,1,1,0,Bureaucratic_Code_4,2016-10-13,Source_7,...,2016,NaT,NaT,2016-12-16,2016-12-16,2016-12-23,2016-12-23,2016 - 12,2016 - 12,1

In [57]:
#genero el CSV
test_agrupado.to_csv(r'C:\Users\licha\Test_Preprocesado_TP2_Datos_2020-2C.csv',index=False , header=True)
train_agrupado.to_csv(r'C:\Users\licha\Train_Preprocesado_TP2_Datos_2020-2C.csv',index=False , header=True)

### Chequeo de dimensiones del set de datos luego de procesarlo

In [58]:
print ("dimensiones del set de test antes de procesarlo:",df_test.shape)
print ("dimensiones del set de test despues de procesarlo:",test_agrupado.shape)

dimensiones del set de test antes de procesarlo: (2551, 51)
dimensiones del set de test despues de procesarlo: (1567, 137)

In [59]:
print ("dimensiones del set de test antes de procesarlo:",df_train.shape)
print ("dimensiones del set de test despues de procesarlo:",train_agrupado.shape)

dimensiones del set de test antes de procesarlo: (16947, 52)
dimensiones del set de test despues de procesarlo: (9841, 146)