In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.legend import Legend
import matplotlib.patches as mpatches
import seaborn as sns
#from statsmodels.graphics.mosaicplot import mosaic
import io
import requests

%matplotlib inline

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
from sklearn import tree

from sklearn.metrics import log_loss

In [72]:
url_train="https://raw.githubusercontent.com/joacols/TP_orga_de_datos/main/Train_Preprocesado_TP2_Datos_2020-2C-encodeado.csv"
s=requests.get(url_train).content
df_train=pd.read_csv(io.StringIO(s.decode('utf-8')))
df_train

,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Account_Created_Date_Day,Account_Created_Date_Month,Account_Created_Date_Year,Opportunity_ID,Sales_Contract_No,...,Bit_Total_Taxable_Amount_Currency_0,Bit_Total_Taxable_Amount_Currency_1,Bit_Total_Taxable_Amount_Currency_2,Bit_Total_Taxable_Amount_Currency_3,Bit_Prod_Category_A_0,Bit_ASP_Currency_0,Bit_ASP_Currency_1,Bit_ASP_Currency_2,Bit_ASP_Currency_3,Bit_ASP_(converted)_Currency_0
0,0,0,0,0,0,1,3,2017,960,0,...,0,0,0,1,1,0,0,0,1,1
1,0,0,0,0,0,1,3,2017,959,0,...,0,0,0,1,1,0,0,0,1,1
2,0,0,0,0,0,1,3,2017,961,0,...,0,0,0,1,1,0,0,0,1,1
3,0,0,0,0,0,1,3,2017,956,0,...,0,0,0,1,1,0,0,0,1,1
4,0,0,0,0,0,19,9,2014,6985,3681,...,0,0,0,1,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9836,1,1,1,1,0,24,1,2017,535,0,...,0,0,0,1,1,0,0,0,1,1
9837,1,1,1,1,0,28,10,2018,9968,0,...,0,0,0,1,1,0,0,0,1,1
9838,1,1,1,1,0,28,10,2018,10157,0,...,0,0,0,1,1,0,0,0,1,1
9839,1,1,1,1,0,3,7,2018,8740,4645,...,0,0,0,1,1,0,0,0,1,1
9840,1,1,1,1,0,13,10,2016,3257,1080,...,0,0,0,1,1,0,0,0,1,1

In [73]:
url_test="https://raw.githubusercontent.com/joacols/TP_orga_de_datos/main/Test_Preprocesado_TP2_Datos_2020-2C-encodeado.csv"
s=requests.get(url_test).content
df_test=pd.read_csv(io.StringIO(s.decode('utf-8')))
df_test

,"Pricing, Delivery_Terms_Quote_Appr","Pricing, Delivery_Terms_Approved",Bureaucratic_Code_0_Approval,Bureaucratic_Code_0_Approved,Submitted_for_Approval,Account_Created_Date_Day,Account_Created_Date_Month,Account_Created_Date_Year,Opportunity_ID,Sales_Contract_No,...,Bit_Total_Taxable_Amount_Currency_0,Bit_Total_Taxable_Amount_Currency_1,Bit_Total_Taxable_Amount_Currency_2,Bit_Total_Taxable_Amount_Currency_3,Bit_Prod_Category_A_0,Bit_ASP_Currency_0,Bit_ASP_Currency_1,Bit_ASP_Currency_2,Bit_ASP_Currency_3,Bit_ASP_(converted)_Currency_0
0,0,0,0,0,0,20,2,2017,12173,0,...,0,0,0,1,1,0,0,0,1,1
1,0,0,0,0,0,22,8,2018,12172,0,...,0,0,0,1,1,0,0,0,1,1
2,0,0,0,0,0,22,8,2018,11408,0,...,0,0,0,1,1,0,0,0,1,1
3,0,0,0,0,0,4,4,2019,12232,0,...,0,0,0,1,1,0,0,0,1,1
4,0,0,0,0,0,4,4,2019,12233,0,...,0,0,0,1,1,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1562,1,1,1,1,0,21,8,2017,11758,0,...,0,0,0,1,1,0,0,0,1,1
1563,1,1,0,0,0,17,10,2018,10721,0,...,0,0,0,1,1,0,0,0,1,1
1564,1,1,1,1,0,15,10,2018,11757,0,...,0,0,0,1,1,0,0,0,1,1
1565,1,1,1,1,0,28,12,2017,10851,0,...,0,0,0,1,1,0,0,0,1,1
1566,1,1,1,1,0,28,12,2017,10880,0,...,0,0,0,1,1,0,0,0,1,1

In [74]:
df_train['Total_Taxable_Amount_Currency'].value_counts()

KeyError: 'Total_Taxable_Amount_Currency'

In [ ]:
df_train.dtypes.head(60)

In [ ]:
from sklearn import preprocessing
lbl = preprocessing.LabelEncoder()
df_train['Sales_Contract_No'] = lbl.fit_transform(df_train['Sales_Contract_No'].astype(str))
df_train['Total_Amount_Currency'] = lbl.fit_transform(df_train['Total_Amount_Currency'].astype(str))
df_train['Total_Taxable_Amount_Currency'] = lbl.fit_transform(df_train['Total_Taxable_Amount_Currency'].astype(str))
df_train['Stage'] = lbl.fit_transform(df_train['Stage'].astype(str))
df_train['Prod_Category_A'] = lbl.fit_transform(df_train['Prod_Category_A'].astype(str))

In [ ]:
x_train=df_train.drop(['Stage','Sales_Contract_No'], axis=1)

In [ ]:
y_train=df_train['Stage']

In [ ]:
x_test=df_test.drop(['Sales_Contract_No'], axis=1)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
neigh = KNeighborsClassifier(n_neighbors=3)

In [ ]:
neigh.fit(x_train, y_train)